### ISSUE TITLE
FSK writer

### ISSUE THREAD

**Issue by OctavioMV** [SiLeBAT/FSK-Lab#105]
1.It has been checked using Guido's model and FSK writer throws an error in legacy node and also in the deprecated one. (The workflow was sent to Miguel some time ago). The error message should be "file could not be created" instead of "file could not created"
[Check_FSKX.zip](https://github.com/SiLeBAT/FSK-Lab/files/1780417/Check_FSKX.zip)
2.with FSK writer is not possible to find FSKX files using the browser.

**Comment by miguelalba** [comment]
Re 2 I was able to browse an FSKX file. But I am not sure which version you used. By the way in the example workflow you attached the spreadsheet is old and cannot be used with the new nodes.

I noticed though that the scripts cannot be used through flow variables in the deprecated creator node while the node manages to read from the local path.

`ERROR FSK Creator (deprecated) 2:68       Execute failed: file:/D:/workspace/Check_FSKX/drop/VirusDecayModel.R: cannot be read`

**Comment by miguelalba** [comment]
I managed to run the deprecated writer node after fixing the spreadsheet. Many of the units used there are wrong and cannot be saved in SBML like unit "0". I also replaced the path to the  deprecated file with an actual filename with extension called *deprecated.fskx* in the *temp_path*.
[Check_FSKX.zip](https://github.com/SiLeBAT/FSK-Lab/files/2428599/Check_FSKX.zip)
