### ISSUE TITLE
Editor bug: Simulation resets when Editor has input

### ISSUE THREAD

**Issue by schuelet** [SiLeBAT/FSK-Lab#1069]
Example Case: 
- Editor is connected to Reader
- Parameter value is changed
- save as default
- **save and close workflow**
- open workflow again
- re-execute Editor
- Bug: In Port-Object, the parameter changes are dismissed and taken from input instead
- Observation: bug only happens to simulation, not metadata itself
- Observation: If disconnected from input, simulation is used from metadata (as it should)

![image.png](https://images.zenhubusercontent.com/5e4ba30f8f780f7f48f8f306/52348d30-9122-4a16-a6e4-645f411b7ce4)
![image.png](https://images.zenhubusercontent.com/5e4ba30f8f780f7f48f8f306/0ea045e8-4389-426a-9eff-b4f79e1f4a9f)

**Comment by ahmadswaid** [comment]
@schuelet I can't reproduce it unfortunately.

**Comment by schuelet** [comment]
resolved
