### ISSUE TITLE
FSK editor (General view)

### ISSUE THREAD

**Issue by OctavioMV** [SiLeBAT/FSK-Lab#107]
**Structure**->It is important to determine the cardinality in each label. For example, within "General information", Creators tab or References Tab must be shown as mandatory.
**Language mode**->Almost all metadata in data “background” in Spanish mode appear in English and in “general information” tab “source” and “status” appear in English.
In German version within “general information” tab “creators”, “references” and “is reference description” within “reference” class are shown in English. Furthermore, in “scope” tab, “hazard” is shown in English and “data background” tab is in English.
Multioption feature is not implemented in dropdown lists.

**Comment by miguelalba** [comment]
The editor node is deprecated and no longer supported.
