### ISSUE TITLE
FSK editor (General information)

### ISSUE THREAD

**Issue by OctavioMV** [SiLeBAT/FSK-Lab#108]
-“Source” is not mandatory.
-“Creator” is not shown as mandatory. Add original google sheet metadata concept (Honorific, name, given name, additional name, family name, organization, telephone, email, country, city, ZIP code, Post office box, street address, extended address and region).
-“Creation Date” is not shown as mandatory.
-“Last modified date” is not shown.
-“URL” is not mandatory.
-“Reference” class is mandatory.
-There is no definitions in reference concepts
-“Model category” and its subclasses are not shown (“Model class”, “model sub-class”, “model class comment” and “basic process”).

**Comment by miguelalba** [comment]
The editor node is deprecated and no longer supported.
