### ISSUE TITLE
FSK editor (Scope)

### ISSUE THREAD

**Issue by OctavioMV** [SiLeBAT/FSK-Lab#109]
-“Product” class:
Use “Product/Matrix” instead of product in the class. Please use the terms provided in the google sheet and do not modify them (only contract them). Use product/matrix instead of environment in concepts within the class.
-“Hazard” class:
“Hazard unit” and “Hazard type” are not mandatory concepts.
“Source of contamination” is not available now.
If you do not have space enough to write the complete name of the concept and contacting it is not enough, you can use the acronym. Please change “no observed adverse” for “NOAEL”.
“LOAEL” concept is not available yet.
-“Population group” class:
”Spatial information” class is not available.
“Population name” is associated to a controlled vocabulary. It is not shown in FSK editor.

**Comment by miguelalba** [comment]
The editor node is deprecated and no longer supported.
