### ISSUE TITLE
FSK editor (Data background)

### ISSUE THREAD

**Issue by OctavioMV** [SiLeBAT/FSK-Lab#110]
-“Study” class:
Add “Study protocol components name”  and "Study protocol components type" instead of “study protocol component”.
 “Study identifier” and “Study title” appear as mandatory but they are not. Only “Study title” is mandatory in case we want to fulfill “Study” field.
-“Dietary assessment method” class:
How should user add more than one option in free text fields?with a comma, point…?

**Comment by miguelalba** [comment]
The editor node is deprecated and no longer supported.
