### ISSUE TITLE
FSK editor (Model Math)

### ISSUE THREAD

**Issue by OctavioMV** [SiLeBAT/FSK-Lab#111]
-“Parameter / Factor / Input / Output / "Data column"” class
Parameter unit category is not mandatory.
-“Quality measures” class: 
Add “sensitivity analysis”.
-“Model equation” class:
Add “Model equation class/distribution”, “Model equation reference” and “hypothesis of the model”. 
About "References" field, it is possible it must be removed. (Not sure) It needs to be asked.
Add “fitting procedure” class
Add “Events” class
Add“Exposure” class and metadata within.

**Comment by miguelalba** [comment]
The editor node is deprecated and no longer supported.
