### ISSUE TITLE
FSK Simulation Configurator

### ISSUE THREAD

**Issue by OctavioMV** [SiLeBAT/FSK-Lab#114]
1. It does not allow to modify values in an already written parameter.
2. It does not allow to modify values in a recent created parameter

**Comment by ahmadswaid** [comment]
Can you please check if the model's parameters have a data type? if not this datatypes should be provided by the user as they are mandatory fields.

**Comment by OctavioMV** [comment]
Yes, it has (double). Now the node does not work when it is connected to fsk creator or fsk editor. Check it in the workflow sent in the ticket 105 "FSK writer".
