### ISSUE TITLE
Update metadata Parameter range of applicability

### ISSUE THREAD

**Issue by mfilter** [SiLeBAT/FSK-Lab#127]
@mfilter: instead of one row we will provide Parameter value min and Parameter value max as free text (cardinality: 0-1) -> inform Octavio / Carolina
@miguelalba : update Creator and Editor nodes
@ahmadswaid : update Simulation Configurator node

**Comment by ahmadswaid** [comment]
All numeric parameters fields in Simulation Configurator node support max&min limit of the parameter.
this is done in SimulatorParamMinMax branch. 
@miguelalba: merge with Master branch.

**Comment by ahmadswaid** [comment]
@miguelalba : Empty min-max values are replaced by Integer.MIN_VALUE and Integer.MAX_VALUE

**Comment by miguelalba** [comment]
Supported in simulation configurator node

**Comment by miguelalba** [comment]
The *FSK Simulation Configurator JS* node needs an update to display minimum and maximum values and allow only values within that range.

**Comment by miguelalba** [comment]
The simulation configurator node displays the minimum and maximum values if set but does not validate yet the entered parameter values.

**Comment by miguelalba** [comment]
Closed by https://github.com/SiLeBAT/FSK-Lab/commit/f40bdacd024ee8e738da8a3fde23945d52a412ef#diff-a9b915fce2053041de7ed01e58667859
