### ISSUE TITLE
Update the controlled vocabulary for "Parameter data types"

### ISSUE THREAD

**Issue by OctavioMV** [SiLeBAT/FSK-Lab#130]
YYYY/MM/DD
and 
YYYY.MM.DD
(because of a problem of compatibility between google sheet and excel)

**Comment by miguelalba** [comment]
Why do not you change the format in the google sheet with dots to match he one in Excel?

**Comment by mfilter** [comment]
I agree, we should discuss this in the context of the update of the controlled vocabulary for "Parameter data types".
https://docs.google.com/spreadsheets/d/1C6N4-YWX9OMmNStd2rYlSUaVys-aiJGLj00cD44aVc8/edit#gid=1809954237 
 So I rename this ticket accordingly.
