### ISSUE TITLE
FSK Simulation Configurator: Provide metadata on each paramater

### ISSUE THREAD

**Issue by mfilter** [SiLeBAT/FSK-Lab#132]
It is necessary to provide additional metadata beside the parameter name to the user. Therefore the parameter unit should be displayed right after the parameter value and all other available metadata should be visible when mouse-over the name.

**Comment by ahmadswaid** [comment]
Done!, all changes have been committed to SimulatorParamMinMax branch.
Test and merge with Master Branch!

**Comment by miguelalba** [comment]
merged at https://github.com/SiLeBAT/FSK-Lab/commit/2bee616f344ad11840ded7111bf8ff123790bbb9
