### ISSUE TITLE
FSK Simulation Configurator: Provide support for vectors and matrices

### ISSUE THREAD

**Issue by mfilter** [SiLeBAT/FSK-Lab#133]
Currently there is no support for input parameters that are vectors or matrices.

**Comment by mfilter** [comment]
An alternative solution would be to replace the Java based Simulation Configurator completely by the JavaScript version of the FSK Simulation Configurator and provide support just in there.

**Comment by ahmadswaid** [comment]
- changes to support the new Datatypes have been made to Parameter Class and (Creator, Editor,  
  Simulation configurator) nodes.
- changes have been committed to the SimulatorDataTypes Branch.
- @miguelalba: please test and merge!

**Comment by miguelalba** [comment]
Add support to other data types such as Dates, File, Boolean, VCards, etc.

https://docs.google.com/spreadsheets/d/1ba8OydZZiv-zwHKyZgsdWG1n8Rb1wDki9lqFtsbDeaU/edit#gid=0

**Comment by miguelalba** [comment]
This old simulator node is deprecated. I believe the new JS node is supporting them. @ahmadswaid can you confirm it?

**Comment by ahmadswaid** [comment]
The new JS simulation configurator is supporting them. but we still miss the validation there
