### ISSUE TITLE
FSK-Writer: write out the calculated values of the model output parameters as dedicated HDF5 files 

### ISSUE THREAD

**Issue by mfilter** [SiLeBAT/FSK-Lab#136]
It would be helpful if the results of a simulation (i.e. the numerical values of each output parameter) can be accessed directly in the generated FSKX file. For example one could create a folder inside the FSKX file for each simulation run that holds HDF5 files for each output parameter.

**Comment by miguelalba** [comment]
HDF support was dropped some time ago.
