### ISSUE TITLE
Create shared resource for testing (Maven, JUnit or similar)

### ISSUE THREAD

**Issue by mfilter** [SiLeBAT/FSK-Lab#138]
As discussed today it would be helpful to have a shared resource that all developers can use for testing new code. This is also relevant as our new software developer intern will start in May.

**Comment by miguelalba** [comment]
The project with test workflows has been updated via 25d0268311a8b29d01fdf8405b306d7efc3bd83e. It lacks though the workflows with google nodes since I could not include the authentication in the workflow setting.

**Comment by miguelalba** [comment]
Now we have a tests module with test plugins. These are the tests executed in every build.
