### ISSUE TITLE
Controlled_Vocabularies_Master_Table: provide data type definition for "Events", "SSE / MSE / RMSE / Rsquared / AIC / BIC", "Fitting procedure"

### ISSUE THREAD

**Issue by mfilter** [SiLeBAT/FSK-Lab#141]
Carolina wrote:  Provide a clear data type definition for "Events", "SSE / MSE / RMSE / Rsquared / AIC / BIC", "Fitting procedure" => this has to go into https://docs.google.com/spreadsheets/d/1C6N4-YWX9OMmNStd2rYlSUaVys-aiJGLj00cD44aVc8/edit#gid=1809954237

**Comment by schuelet** [comment]
@mfilter There is a definition. Is it enough to close this ticket?

**Comment by mfilter** [comment]
ok
