### ISSUE TITLE
FSK reader (deprecated) does not read model in newer KNIME

### ISSUE THREAD

**Issue by tasjabfr** [SiLeBAT/FSK-Lab#148]
runs in KNIME-externer Server but not locally in newer Version

[ticket_miguel.zip](https://github.com/SiLeBAT/FSK-Lab/files/1898616/ticket_miguel.zip)

**Comment by miguelalba** [comment]
The reader node is failing to retrieve the minimum and maximum values of the output variable *expected.temp* which are missing in the SBML file within the FSKX archive. Could I see the metadata spreadsheet used for this model?

I edited the SBML file by adding an SBML contrain with the minimum and maximum values. [metaData.zip](https://github.com/SiLeBAT/FSK-Lab/files/1898750/metaData.zip)

By the way once the file is read I can see that the parameter scripts has two illegal values. The expressions are not supported in the deprecated reader.
```
mu.start <- mu.init - 0.3
sd.start <- max (sd.init - 0.3,-0.05)
```
These two variables need to be replaced with literal values.
