### ISSUE TITLE
FSK Creator (deprecated)

### ISSUE THREAD

**Issue by OctavioMV** [SiLeBAT/FSK-Lab#149]
Error in the library. To solve it, de-install library and re-install in r.

**Comment by mfilter** [comment]
Hi Octavio,
could you please describe the issue a bit more ? For me it is unclear what library and what error message you refer to.
Thx.

**Comment by OctavioMV** [comment]
The feature of uploading libraries does not work properly in this node. Due to that, the node does not run even though it is well configurated. That means that an already installed library is not recognized by the node and the library must be deinstalled and reinstalled to make the node works.

**Comment by miguelalba** [comment]
New build under https://dl.bintray.com/silebat/fsklab_icpmf. Please update and check.
