### ISSUE TITLE
Update and sort controlled vocabulary list for "Publication type" in "FSK editor" node

### ISSUE THREAD

**Issue by tasjabfr** [SiLeBAT/FSK-Lab#151]
I realized that the controlled vocabularies under Publication type in the editor node are not consistent with our controlled vocabularies master table. They are also not sorted alphabetcically.

**Comment by miguelalba** [comment]
Updated vocabularies to [1.0.4](https://docs.google.com/spreadsheets/d/1C6N4-YWX9OMmNStd2rYlSUaVys-aiJGLj00cD44aVc8/edit#gid=1479548673) via https://github.com/SiLeBAT/FSK-Lab/commit/4ab41f49abf8b5cbf7e57daba8570954b656e39b
