### ISSUE TITLE
need a way to load in additional files into the creatore node in the webportal

### ISSUE THREAD

**Issue by llavall** [SiLeBAT/FSK-Lab#156]
The file tab in the creator node supports to load in additional files in a local knime installation. Since there is no solution yet to do that in the webportal (this option does not support flow variables) Miguel offered to create a second in-port which can handle a list of files. In the webportal I would allow the user to upload a zip-file, uncompress it and use the list files node to provide the files to the new inport. It might not be the best solution but it might be the fastes for Miguel - a javascript version of the creator node is more difficult and supporting flow variables seem to be difficult here too.

**Comment by mfilter** [comment]
I wonder why this worked in the old portal and does not work now?

**Comment by llavall** [comment]
In the old portal we never did support to include addtitional files inside the FSK-creator - only the 3 script files and the excel-file.

**Comment by mfilter** [comment]
OK. Then go ahead if this works

**Comment by miguelalba** [comment]
This was addressed in commit f4304b3. It is described carefully in the commit log but the most relevant part for you @llavall is:

> Creator node may now include a reference to a working directory
with resource files. These resource files are not copied through
node instances but only the reference to the local path of the
working directory resulting in faster loading times for nodes using
resources.

> Since this setting is a string variable it may be configured with
a flow variable and used in the KNIME server as long as the
working directory is recreated in the server.

Please check and close ticket.
