### ISSUE TITLE
FSK creator does not recognize the path in the "working directory" 

### ISSUE THREAD

**Issue by OctavioMV** [SiLeBAT/FSK-Lab#161]
FSK creator does not recognize the path in the "working directory" when it is provided in the tap "options" of the node.

**Comment by miguelalba** [comment]
Fixed via b73739a. There was a bug in the GUI code of the creator preventing the value entered in the dialog to be saved and therefore always saving an empty string which stands for no working directory set. A new build has been uploaded with this fix to the ICPMF update site.

This fix has been tested on a simple model from Guido that loads a string variable holding "Hello World" that is used in the visualisation script, using this string as the title of the plot. The same model has been tested in four scenarios where the working directory is set either:
1. by a flow variable
2. by a local path: absolute path in the filesystem, like `C:/Users/klopp`
3. by an absolute URL: relative path to workspace. E.g. `knife://LOCAL/ResourcesWF/resources`
4. by a mountpoint-relative URL. E.g. `knime://LOCAL/ResourcesWF/resources`

@OctavioMV You can test the attached workflow [ResourcesWF.knwf.zip](https://github.com/SiLeBAT/FSK-Lab/files/2046180/ResourcesWF.knwf.zip). Just unzip and import it. The only scenario that needs to be configured is the full path where you need to change to your folder according to your filesystem and location of the workspace. See the path in the node for reference. The other scenarios do not need to be changed (they are relative). Please test and close the ticket.

Best,
Miguel

**Comment by miguelalba** [comment]
The writer node was not supporting relative paths (as used by the flow variable) to reference the working directory. It is been fixed in df49542 and a new build released. I tested it against the four scenarios described above.
[ResourcesWF.knwf.zip](https://github.com/SiLeBAT/FSK-Lab/files/2047146/ResourcesWF.knwf.zip)

@OctavioMV Like before, please test and close ticket.

**Comment by OctavioMV** [comment]
@mfilter Thank you for informing me about the problem with Ahmad version. The FSK writer works again.
