### ISSUE TITLE
JS Simulation Configurator throws error on knime server

### ISSUE THREAD

**Issue by tasjabfr** [SiLeBAT/FSK-Lab#164]
Error message: nullpointer exception: null

Please find attached the workflow and files. 

If we unwarp the JS Simulation configurator there is no error on knime server. 

[drop.zip](https://github.com/SiLeBAT/FSK-Lab/files/2048739/drop.zip)

[2._Online_Creation_of_Harmonized_Models_example.knwf.zip](https://github.com/SiLeBAT/FSK-Lab/files/2048743/2._Online_Creation_of_Harmonized_Models_example.knwf.zip)

**Comment by ahmadswaid** [comment]
This workflow contains already a drop folder, where to use the one you have attached here?
Another thing: Is there more information about the error on the server, because I don't have access to the server from here, maybe the log file from the server.

**Comment by tasjabfr** [comment]
Hi Ahmad. The drop.zip folder contains all the files you need to upload in the first and second node of  the workflow (first and second user input). We just sent them to make sure that you can execute the workflow locally in exactly the same way we do on the server. Unfortunately, we do not get a detailed error message on the server. The only message we get is the nullpointer exception: null. HTH, Tasja

**Comment by miguelalba** [comment]
I created a simpler version of the WF with the nodes:
1. String input: Sheet name
2. FSK Creator
3. FSK Editor JS
4. Simulation Configurator: NPE in webportal
5. Runner: Picks simulation entered in simulator

In the original WF the creator has the comment:
> cant use the new xls file!

In this workflow I can. The spreadsheet is named `testDose Response NoV QRA Model Annotation Excel templateV1.03 .xlsx` and I had to change the sheet name to `Generic Metadata Schema`. Maybe that was the error in the original WF?
[tasjaWF.zip](https://github.com/SiLeBAT/FSK-Lab/files/2054642/tasjaWF.zip)

**Comment by miguelalba** [comment]
@tasjabfr I got the following error when running your model in RStudio.

source('parameter_script_DR_ResultsFile_nvec10_nloop1.R')
source('model_script_DR_ResultsFile_nvec10_nloop1.R')
4 
1
Error in gzfile(file) : invalid 'description' argument

**Comment by tasjabfr** [comment]
HI Miguel. Thank you for looking into this. I am a little confused because we all agreed that we would use the template V1.03. Octavio is alos using it in all of his workflows.... I am not sure what is wrong with the Excel sheet I used? It is unclear to me what causes this error. 

Concerning the error in R we got the same yesterday and we fixed it. I am testing everything now with teh enw update and will come back to you if I run into problems....

**Comment by miguelalba** [comment]
Hi Tasja. The creator is using the 1.03 as agreed. I checked it in your WF and it worked for me. All I changed was the flow variable `sheet` containing the name of the sheet. The old spreadsheets have a *Generic Metadata* sheet IIRC while the new spreadsheet from Octavio has the sheet `Generic Metadata Schema`.

You can check in the WF I attached before https://github.com/SiLeBAT/FSK-Lab/files/2054642/tasjaWF.zip.

**Comment by tasjabfr** [comment]
It seems weird to me because we had a string input defining Generic Metadata Schema, so I am not sure what went wrong....

**Comment by miguelalba** [comment]
Hi Tasja. I downloaded again the WF and files in drop and got again the same error. Did you change the file? If not, could you please sent me the fixed model? Thanks

`> setwd("~/Downloads/drop")`
`> source('parameter_script_DR_ResultsFile_nvec10_nloop1.R')`
`> source('model_script_DR_ResultsFile_nvec10_nloop1.R')`
`4` 
`1`
`Error in gzfile(file) : invalid 'description' argument`
`> source('visualization_script_DR_ResultsFile_nvec10_nloop1.R')`
`Error in as.matrix(d) : object 'res_df' not found`

**Comment by tasjabfr** [comment]
HEre is the updated version. The temp directory node and the unzip node are alos used by Lars on the server. 
[Dose_response_Nov_QRA_Creator_new_Miguel.zip](https://github.com/SiLeBAT/FSK-Lab/files/2058005/Dose_response_Nov_QRA_Creator_new_Miguel.zip)
