### ISSUE TITLE
Matrix as input parameter results in error during creation of fskx file on server

### ISSUE THREAD

**Issue by tasjabfr** [SiLeBAT/FSK-Lab#167]
I have been trying to create FSKX files of a dose response model that uses a matrix (with numbers) as an input with WF2 on the FSK Web Server. Unfortunately this is resulting in an error. 

I think the error occurs in the "configuration simualtor", because the  matrix is defined as an input in the "model annotation template" without a corresponding parameter in the "parameter sheet". This creates an empty parameter value for the matrix in the "configuration simualtor".

When I take the matrix out of the "model annotation template" I have no problems creating FSKX files. 

I have attached two zip folders with files for model creation. One folder **with** the matrix in the "model annotation template" (DR_w_matrix) and another **without** the matrix in the "model annotation template" (DR_wo_matrix).

[DR_wo_matrix.zip](https://github.com/SiLeBAT/FSK-Lab/files/2062784/DR_wo_matrix.zip)
[DR_w_matrix.zip](https://github.com/SiLeBAT/FSK-Lab/files/2062785/DR_w_matrix.zip)

I think it would be great if we could fix this bug, becasue Octavio and I have many models that have matrices or vectors as inputs and we have to define them in the "model annotation template" so that the user knows that this input is required. 

Please let me know if you need more info or if I was unclear. Thank you!

**Comment by miguelalba** [comment]
Fixed in ea971d6f4c1571d426db4bcf632e6bfd4d151f79. A new build is available.
