### ISSUE TITLE
FSK Simulation Configurator is not working

### ISSUE THREAD

**Issue by mfilter** [SiLeBAT/FSK-Lab#168]
see attached workflow. The JavaScript version of the node works fine, the Java version not.
[TestModelOctavio2.zip](https://github.com/SiLeBAT/FSK-Lab/files/2072054/TestModelOctavio2.zip)

**Comment by ahmadswaid** [comment]
The simulation configurator is using the ParameterName instead of the ParameterID during getting the parameter from the parameterMap Object.

This is solved in the branch (java_simulator_refactor).
@miguelalba please test and close the ticket!

**Comment by miguelalba** [comment]
Fixed in 1fada9f7511d871ec1e276d9d75988e10cc366d1
