### ISSUE TITLE
Saving PNG file with plot in the FSKX file

### ISSUE THREAD

**Issue by miguelalba** [SiLeBAT/FSK-Lab#172]
* The writer node must include a PNG file with the plot if present.
* The reader node initially ignores this file.

# FSKPortObject needs an update
* Since the runner node only has an input (FSK) the plot must be passed in the FSK port object.
* Deep copies of the plot should be avoided. Otherwise loading and saving the port object would take too long. A Java Path should be used instead. This path would keep a temporary file created outside the port object, in the runner node.
* Since the path of the PNG file links to a temporary file it is not necessary to support relative paths. Users will never set it up through a flow variable.
* The serializer of the FskPortObject must not fail. Since the png file is optional (not all the models create plots), the serializer cannot expect always the path. Besides, old port object without plots must be supported.

# Supported file types
Currently the runner node only generates PNG files.

# FSKX library
An URI for PNG is required. MIME type:  `image/png`.

**Comment by tasjabfr** [comment]
It would be nice if it was possible to save more than one image of a plot within the FSKX file. These images could be generated in the model script and written into the working directory. I am not sure if this is possible, but the models that I have been dealing with often create more than one plot to visualize results and it would be nice if those could be saved in the FSKX file.

**Comment by tasjabfr** [comment]
As examples you could write the following in the model script:

png(filename="your/file/location/name.png")
plot(x,y)
dev.off()

This is possible for all simple plotting functions in R and for the follwoing fromats: png, bmp, jpeg and tiff as well as for pdf.


If we use ggplot2 we have to use dev.print like this: 

dev.print(pdf, 'filename.pdf')

HTH,
Tasja

**Comment by miguelalba** [comment]
I am not comfortable supporting PDFs as the creator might receive an update to include a certain paper and it could be messy in the end dealing with papers provided by the user and pdfs generated in the model script. I would avoid it until the uses cases are more defined. Are you using the pdf function or know of any model that is using it?

Regarding the images, there is no problem and I can add them. The formats would be:
* bmp
* jpeg 
* png
* tiff

With *png* files we need to keep in mind that the Writer node is saving the plot from the visualization script with name *plot.png*. Therefore any plot generated in the model script with that name would be overwritten. I think for now it is enough to include a warning in the node description. A solution could be to use a random name for the model plot but I believe @llavall is using the *plot.png* filename in his workflows.

**Comment by tasjabfr** [comment]
It is totally okay with me not to use PDF.

**Comment by miguelalba** [comment]
It is implemented in https://github.com/SiLeBAT/FSK-Lab/commit/91eead29560e7bf5f9da5d4b48d61049961a7ad7 and a new build is available with the feature. There is a bug still though. The generated images are not saved when the working directory is not defined in the creator node.

I will need to re use the temporary working directory used by the runner when the user does not define one. But this bug comes from the runner and will take longer. In the mean time every time that you want to store the images (even when you do not have resources) specifiy the working directory in the creator.
