### ISSUE TITLE
Installation of R-libraries in FSK-Lab does not work when "require()" is used instead of "library()"

### ISSUE THREAD

**Issue by tasjabfr** [SiLeBAT/FSK-Lab#182]
I had some problems runnign one of Octavio's models (VIZDR_Tool_Model) in my FSK_lab and I found out thats this was related to mising libraries. 

The R code that calls the libraries is written like this: 
if("stats4" %in% rownames(installed.packages()) == FALSE)
{install.packages("stats4"); require(stats4)} else{require(stats4)}
if("boot" %in% rownames(installed.packages()) == FALSE)
{install.packages("boot"); require(boot)} else{require(boot)}
if("car" %in% rownames(installed.packages()) == FALSE)
{install.packages("car"); require(car)} else{require(car)}

In this case "require()" is used to call a library and the libraries are not automatically installed in FSK-Lab.

When I change the code to this: 
library("stats4")
library("boot")
library("car")

The libraries are installed without problem. 

Would it be possible to make sure that FSK-Lab also recognizes "require()" for automatic library installation?

**Comment by tasjabfr** [comment]
Hi again,
I have just tried with require at the begging of the line like this: 

require("stats4")
require("boot")
require("car")

And it did not work.

**Comment by llavall** [comment]
This issue might be the same as in #222

**Comment by mczyzj** [comment]
http://www.vikram-baliga.com/blog/2015/7/19/a-hassle-free-way-to-verify-that-r-packages-are-installed-and-loaded
