### ISSUE TITLE
Include model annotation excel template in FSKX file

### ISSUE THREAD

**Issue by tasjabfr** [SiLeBAT/FSK-Lab#184]
It would be very useful if we could write the model annotation sheet (Excel) into the FSKX file. This would help users to e.g. change model parameters or re-annotate a model.

Thanks! 
Tasja

**Comment by miguelalba** [comment]
Affected classes (may be more):
- FskPortObject
- CreatorNodeModel
- JoinerNodeModel
- JSSimulatorNodeModel
- ReaderNodeModel
- RunnerNodeModel
- SimulatorNodeModel
- WriterNodeModel

**Comment by miguelalba** [comment]
Included in build in the https://dl.bintray.com/silebat/fsklab_icpmf update site.
