### ISSUE TITLE
Simulation configurator bug with constant Parameters

### ISSUE THREAD

**Issue by schuelet** [SiLeBAT/FSK-Lab#195]
the fsk simulation configurator (js) seems to obmit parameters that are classified as "constant".
[constantParametersBug.zip](https://github.com/SiLeBAT/FSK-Lab/files/2163033/constantParametersBug.zip)

**Comment by mfilter** [comment]
This is not a bug. This is a feature.
A constant should remain constant and should not be changed by the user.
HTH

**Comment by schuelet** [comment]
The fsk simulation configurator completely removes constant parameters from the simulation tab, meaning they seem to be no longer part of the fsk Object -> fsk runner doesn't run the model anymore

**Comment by mfilter** [comment]
This is indeed an issue. However we should clarify first, what is defined in the FSK-ML guidelines.
Do the SED-ML file contain only information on "Input" parameters (then the information on parameters defined as Constant or Output is not found in there) or do we expect, that these parameters are defined in the SED-ML file as well (then the fsk simulation configurator JS needs to pass this information also into the newly generated SED-ML file).
HTH
