### ISSUE TITLE
metadata-json does not provide empty strings for missing values

### ISSUE THREAD

**Issue by llavall** [SiLeBAT/FSK-Lab#201]
I know understand why my workflow runs into an error if for example no Software (not mandatory at the moment) is mentioned in the Excel file and therefore the information is missing in the generated FSKX-file. I expected that the json-extractor would just receive an empty string (what happens if I just delete the entry with an FSK-Editor;  like "software" : "" instead of "software" : "FSK-Lab". 

But now I realize that the complete line/information is not present in the JSON if the information was not provided via Excel sheet.

I would like to ask if this is wanted this way to keep the json small. I just did not expect it.

Lars

**Comment by miguelalba** [comment]
Yes. IIRC EMF is using a pre configured JSON parser that generates minimised metadata and blank fields are ignored. I believe you could set an empty string with a KNIME Json node.

**Comment by miguelalba** [comment]
I think you fixed your workflow. @llavall can I close this?
