### ISSUE TITLE
since the normal FSK editor does not work anymore - remove or deprecate?

### ISSUE THREAD

**Issue by llavall** [SiLeBAT/FSK-Lab#202]
I was wondering if we should somehow remove FSK nodes from the FSK node repository which does not work at all, or at least mark them somehow.

**Comment by miguelalba** [comment]
There might be errors with the legacy and deprecated nodes. I only tested the new nodes. Unfortunately I do not have workflows using the old nodes which by the way require old metadata.

When you find errors you can report it here and I will look into it.

**Comment by miguelalba** [comment]
@mfilter should I also deprecate the Java Simulation Configurator node?

**Comment by mfilter** [comment]
Yes, I think there is no other reasonable solution. Or do you plan to maintain the Java Simulation Configurator in the future?

**Comment by miguelalba** [comment]
Both are deprecated
