### ISSUE TITLE
provide rule list and changelog

### ISSUE THREAD

**Issue by llavall** [SiLeBAT/FSK-Lab#210]
I would like to link in my workflows to a list which tells the model creator what rules to taken care of, like don't mix capital letters or make sure the order of parameter makes sense (from the latest issue with the 'Step' versus 'step' and 'a<-c(step,2)' and 'step <-1'.

Were could we place this list in a meaningful form? Miguel should have easy access in order to update the list regularly. Maybe here on github? We could then link to this page from foodrisklabs as well.

I would like to have the same for a so called changelog ( like https://github.com/olivierlacan/keep-a-changelog/blob/master/CHANGELOG.md ). It should always include the changes regarding the last build and include hints if behavior has changed. I hope this will help the user and us more to understand what happened and what to take care of.

Best wishes
Lars

**Comment by llavall** [comment]
Just want to list the link to the rules list here too: https://github.com/SiLeBAT/FSK-Lab/wiki/Writing-R-code-compatible-with-FSK-Lab

The list a good starting point. Would be great if you all could further improve it in order to avoid misunderstandings. 

As ex

**Comment by mfilter** [comment]
Could we share this link also on the FSK-Lab website https://foodrisklabs.bfr.bund.de/fsk-lab_de/ ?

**Comment by llavall** [comment]
https://github.com/SiLeBAT/FSK-Lab/blob/master/changelog.md

**Comment by llavall** [comment]
I run a model from Inés and it shows how we don't want a model to be on the server:
- It uses a really big vector which needs a huge amount of memory 10 to 20GB?- therefore it can't be run on a normal PC if the needed high numbers are used.
- It seems to utilize only one CPU and this on a low level.  
- Running time is more then an hour  - it really needs to be optimised for FSK.

I suggest that we elongate the rule list with a nice to have list like:
- optimise RAM use to not exeed a certain limit.
- optimise to use multiple cores (minus one)

**Comment by llavall** [comment]
https://github.com/SiLeBAT/FSK-Lab/blob/master/changelog.md is not working anymore!

We need a clear defined place for the changelog which is very easy to find for the user!

In addition there is the need to inform the test group about the recent changes as well as the user in the productive version -> leads to two versions of the changelog?
