### ISSUE TITLE
list all plugins needed to run a model in a file

### ISSUE THREAD

**Issue by llavall** [SiLeBAT/FSK-Lab#212]
The idea is that this information is already handled internally in FSKlab, but not easily accessible and machinereadable from "outside". I have in mind that we can use the stored information in the VRE, in order to automatically install needed plugins for us. They would read in a file plugins.json from an uploaded model and install the mentioned plugins for us. This is somehow related to #208 .
Best wishes Lars

**Comment by llavall** [comment]
could be also packages.json

**Comment by ahmadswaid** [comment]
a solution was provided in V 1.3.0
