### ISSUE TITLE
Compilation errors in CombinedFskPortObject

### ISSUE THREAD

**Issue by miguelalba** [SiLeBAT/FSK-Lab#215]
Compilation errors in master branch. Please fix asap.

![grafik](https://user-images.githubusercontent.com/19906968/43719879-3f203fa8-998f-11e8-9640-5174b4e0c4c8.png)

**Comment by ahmadswaid** [comment]
The constructor and the method referred are in the master branch.
I don't have those error you refer to.

**Comment by miguelalba** [comment]
Sorry. It went away with cleaning the project.
