### ISSUE TITLE
Concept needed for model ID in FSK Repository

### ISSUE THREAD

**Issue by llavall** [SiLeBAT/FSK-Lab#220]
The repository has a column for the model ID. At the moment there are two models uploaded by Octavio with the very same ID. I assume they were derived from the same model and thats why the ID was used twice. 

In my understanding a model ID should be unique and represent the model.
Since in the future the model ID should be generated by the system, I suggest that we use a hash ( https://en.wikipedia.org/wiki/Hash_function ) of the model code itself. 
This way we get an automatic generated hash code which is unique for the model. If the model code is changed in one single place the hash code will change too.
This could be also used as a key or certificate in order to determine/proof that we are still dealing with the original model as the author was implementing it.

(I am aware that this is not an absolutely secure technique, but I think it will serve our purpose).

The way I am suggesting using a hash code, there will be no change if the parameter are changed or the visualisation script. It might be useful to also apply hashes there.

Maybe we could provide the hashes not just in the json, but also in the new versions tab.

Best Lars

**Comment by mfilter** [comment]
A hash could be a solution. In PMM-Lab we autogenerate a UID. It should be something that we can implement in the Google Template as well.

**Comment by llavall** [comment]
In my idea the hashes are always live created by the FSKlab nodes. Since the Google sheet is used before the model has been created and there is no back channel, I don't know how that would work out.

**Comment by schuelet** [comment]
covered by #95
