### ISSUE TITLE
Is there an idea on how to validate the model results?

### ISSUE THREAD

**Issue by llavall** [SiLeBAT/FSK-Lab#221]
When I was working with Tasja on the NoV model, we had the issue that we were not sure about the right model results. There was a paper which gave a overview over the expected results but it turned out they did number the results in a misleading way and they forgot to calculate the result times 0.8 in the model.

I am wondering if we could establish a system on validating a model, e.g. the modeler has to provide different scenarios (sets of parameter) and the expected results (at least an area where to expect the result). I assume this will lead to problems if a model output is a png only or other files, but maybe we find a way.

I really like the function of KNIME to provide executed workflows and I am also wondering if we could apply that for our purpose as well. Right now we only share not executed models but it might be useful for the stakeholders and the jury who accepts models and also for our testing purposes.

Best Lars

**Comment by mfilter** [comment]
Unfortunately there is no real solution to that. For sure I'm in favour of saving the whole workflow into the FSKX file as well, or at least provide this as an option in the FSKX Writer node. For sure this might increase the file size.
