### ISSUE TITLE
Working Directory created only when we run  the reader!

### ISSUE THREAD

**Issue by ahmadswaid** [SiLeBAT/FSK-Lab#223]
I have noticed that if I created Workflow which reads a .fskx file and try to run using the runner everything is OK. but if I close Knime saving my workflow:
1- Knime will save the state of my workflow which have executed reader node.
2- Also any working directory created by the reader will be deleted because they are created as temp folder.

After that, if start Knime again and try to reset and run the runner only, I will get an error saying that the working directory can't be set by R and this is correct because this directory does not exist anymore.

@mfilter: I'm wondering if we have to check the working directory again in the runner to be sure it's there and if not, we create it again.

**Comment by ahmadswaid** [comment]
I think even rechecking the folder in the runner will not solve the problem. since the .fskx file is not available to the runner so the runner can't recreate the folder with its contents.
Maybe the only solution to have the working directory as a normal folder and not as a temporary folder.

**Comment by mfilter** [comment]
I agree, we should have this as normal folder, maybe we can include it into the folder of the KNIME workflow right away?

**Comment by schuelet** [comment]
fixed with environmentManager Implementation, available on ICPMF and 2.0
