### ISSUE TITLE
FSK-Lab does have problems with the knime protocol knime://

### ISSUE THREAD

**Issue by llavall** [SiLeBAT/FSK-Lab#255]
After a long time fighting with the REST API and endless discussions with KNIME I started from the scratch and figured out, that I am dependend on the the KNIME protocol which does not fully work on the server if FSK-Lab nodes are used to write files.

I run two workflows I created on the server and the server KNIME.  Both finish as expected in the server KNIME, but only the one which uses KNIME nodes only can finish as expected in the Server.

https://vm-maslxknime02.bfr.bund.de/knime/#/testing/Lars_testing/testwriteanddownload2 does create a table file in the folder FSK-Web/temp/table.test which can be seen via the connected KNIME explorer if present (knime://knime.mountpoint/FSK-Web/temp/test.table).

https://vm-maslxknime02.bfr.bund.de/knime/#/testing/Lars_testing/testwriteanddownload does create a fskx file in the folder FSK-Web/temp/test.fskx which can be seen via the connected KNIME explorer if present (knime://knime.mountpoint/FSK-Web/temp/test.fskx).

It would be great if you could fix that for me, in order to finally use the full capability of the server. And please check if that also applies for the reader node.

Thanks a lot
Lars

PS. Same issue on the external server - seems not to be related with the plugin version used https://knime.bfr.berlin/knime/#/testing/Lars/testknimeprotocollfsk
(knime://knime.mountpoint/temp/test.fskx)

Error message is the good old: Execute failed: ("NullPointerException"): null

**Comment by miguelalba** [comment]
The Writer node is returning *null* for external urls. The urls with the *knime://* protocol seem to work online although for some obscure reason they are considered external in the server. If an external URL is used I am throwing an *InvalidSettingsException* with text: External URLs are not supported.

I made the changes in the branch [knime protocol](https://github.com/SiLeBAT/FSK-Lab/commit/86eae83ef803fe2992dc833a285f506cb1aa849f) and after checking the code of the Table Writer node from https://github.com/knime/knime-core/blob/master/org.knime.base/src/org/knime/base/node/io/table/write/WriteTableNodeModel.java.

**Comment by mfilter** [comment]
@miguelalba : am I right that you now check if this solves the issue on the server? I guess KNIME's Table Writer node works as expected on the server?

**Comment by llavall** [comment]
@mfilter 
Ahmad and Miguel are working on that. The issue is that the knime protocol "knime://knime.mountpoint" does work as expected locally in KNIME, but not on the server. The reason is, that all things happening on the server are secretly done via REST interface and that was not implemented this way in our nodes yet.

Since I need this feature we have to fully include it in our nodes as well. So far my old way of writing FSKX files in the server with an absolute path still works as we are used to it, but files written without the knime protocol are not visible via the server or REST API.

**Comment by miguelalba** [comment]
The new feature was tested in the internal server and will be merged into master. Hooray!
