### ISSUE TITLE
I introduced the label 'FSK-Lab' to be used for all issues related to FSK nodes

### ISSUE THREAD

**Issue by llavall** [SiLeBAT/FSK-Lab#256]
@miguelalba could you please apply that to old ticktes too, in order to get a better filter option and overview. I am wondering if there is the option to open sub projects like in GITLAB?

**Comment by miguelalba** [comment]
I assigned the FSK-Lab to the open FSK-Lab tickets. As far as I know there are only sub projects in Git but not GitHub. Please see https://blog.github.com/2016-02-01-working-with-submodules/
