### ISSUE TITLE
Wrong access of methods in FskEditorJSNodeModel

### ISSUE THREAD

**Issue by miguelalba** [SiLeBAT/FSK-Lab#281]
Methods only used in a class should be private! The methods *downloadFileToWorkingDir* and *connectAndDownloadFilesOnServer* were given public access.

From https://docs.oracle.com/javase/tutorial/java/javaOO/accesscontrol.html:
> Use the most restrictive access level that makes sense for a particular member. **Use private unless you have a good reason not to.**

**Comment by ahmadswaid** [comment]
This code is still under experiment.
