### ISSUE TITLE
PMF Writer gives Null Pointer Exceptions

### ISSUE THREAD

**Issue by mfilter** [SiLeBAT/FSK-Lab#287]
If I reset the PMF Writer nodes in attached workflow (the suffix was manually changed to .zip from .knar in order to be able to attach it here) there are Null Pointer Exceptions:
ERROR PMF Writer           0:275      Execute failed: Tertiary Model_HuNoV.pmfx could not be opened
ERROR PMF Writer           0:273      Execute failed: ("CombineArchiveException"): null

[Bartsch et al., 2018.zip](https://github.com/SiLeBAT/FSK-Lab/files/2559524/Bartsch.et.al.2018.zip)

**Comment by mfilter** [comment]
new version of the workflow 
[Bartsch et al., 2018.zip](https://github.com/SiLeBAT/FSK-Lab/files/2560979/Bartsch.et.al.2018.zip)
in executed status

**Comment by miguelalba** [comment]
PMF Writer throws meaningful error when an unit used in a model is not
found in DB. E.g. "Unit could not be found in DB: log10 count"
