### ISSUE TITLE
Workflow exporter should allow to choose to save data

### ISSUE THREAD

**Issue by llavall** [SiLeBAT/FSK-Lab#291]
I would like to have a setting to choose if I want to save the executed mode or not - like in workflow export of KNIME

**Comment by schuelet** [comment]
@llavall what is this workflow exporter? Still a thing or can we let it go?

**Comment by llavall** [comment]
This is related to a functionality that Ahmad delevoped a while ago. You could export a workflow as a FSK model. Don't know the status of that feature, guess @ahmadswaid  and @mfilter know more about.

**Comment by mfilter** [comment]
I think we can close the ticket.
Nevertheless, we use the work related to that as a starting point to support the exchange of KNIME-based models via FSKX.
For now this has low prio.
