### ISSUE TITLE
FSK Editor is not able to change the working directory if it's already set!

### ISSUE THREAD

**Issue by ahmadswaid** [SiLeBAT/FSK-Lab#305]
Editing the working directory of pre-existing and configured FSK model with a  working directory is not possible!

**Comment by schuelet** [comment]
@miguelalba Do you think this is worth keeping? Or does the environmentManager take care of it?

**Comment by miguelalba** [comment]
Environments can be edited but it is better to just create and assign a new environment.

**Comment by schuelet** [comment]
issue is fixed with https://github.com/SiLeBAT/FSK-Lab/pull/994
