### ISSUE TITLE
fsk can't read a remote file on testserver?

### ISSUE THREAD

**Issue by llavall** [SiLeBAT/FSK-Lab#306]
`https://vm-maslxknime02.bfr.bund.de/knime/#/VRE/simulation_settings?exec=fd126611-bef0-40b0-a398-fe9a01b10cec`

**Comment by llavall** [comment]
The problem is on the server side, Knime seems to misunderstand the configuration.

**Comment by miguelalba** [comment]
If I understood correctly the reader node on the server cannot read an http url that could not be loaded either with KNIME nodes. Thus, can we close this?
