### ISSUE TITLE
1.4.5 release

### ISSUE THREAD

**Issue by miguelalba** [SiLeBAT/FSK-Lab#308]
There is a new build on the test update site with the 1.4.5 build.

## Changed
- Add KNIME dependencies *org.knime.ext.r.type* and *org.knime.ext.r.bin* as included plugins so that the KNIME update site is not necessary. Before it would fail when the user does not have this update site or it has been disabled.

### Fixed
- Fix the tree view of the model script in Joiner JS.
- Load 32-bits R bundle on x86 Windows
- Make visualization scripts optional in the creator node.

This ticket is meant for reporting potential issues in this version.

**Comment by mfilter** [comment]
I just installed the latest update on my private PC (windows 64 bit)
The result is, that the FSK-Lab R path was correct, but when I press "Restore default" I got the error "Path to R Home does not contain a folder with name 'bin'."
I use KNIME 3.7.1 and have only  R 3.4.4 for 64-bit Windows	3.4.4.201808071522 installed.

**Comment by mfilter** [comment]
I now tested another KNIME instance I installed and tested on 03.02 (the one I had reported on last time).
Even after installing today's update the FSK's R home was still not set and the Restore Update did not work.
Even the regular R home (from the KNIME R scripting extension) is not set !

**Comment by llavall** [comment]
https://github.com/SiLeBAT/FSK-Lab/issues/307

**Comment by estilag** [comment]
Installation works now in my office PC.

**Comment by llavall** [comment]
Tasja, Esti and I were testing a workflow on each on our machines, which failed while using the creator (node #12) . What happened inside is not clear to us, but as soon as the creator node was run the Excel file used was corrupted and changed file size from 3.4 MB to 1.4 MB and was not readable anymore, causing the node to fail.

I zipped and uploaded my KNIME to showcase and will mail you the link to it for later investigations.

[newModelsTest.knwf.zip](https://github.com/SiLeBAT/FSK-Lab/files/2879816/newModelsTest.knwf.zip)

As far as we understood Miguel, that still is a known issue in all versions.
