### ISSUE TITLE
Runner fails if internal R is used but works with external R

### ISSUE THREAD

**Issue by tasjabfr** [SiLeBAT/FSK-Lab#317]
Running the full Norovirus model leads to a 

`ERROR FSK Runner           0:36       Execute failed: Error: expr # 25 "foreach(Loop = 1:nLoop) %dopar% {`

in the internal R (with FSK installed).

If then switched to an external R it works. 

Switching back to internal again and it works.

Restarting KNIME with this setting and the error appears again.

the following model was used with the default settings:
`knime://Externaltestserver/FSK-Web/newfiles/20180814151150full_NoV_QMRA.fskx`

**Comment by mfilter** [comment]
I can reproduce these findings.
After looking into the code my gut feeling is, that that the FSK-Runner has problems with the parallel execution of a loop. ( as if you replace the foreach statement with the original for() loop it works.)

**Comment by mfilter** [comment]
Further findings: 
I used the R Scripting nodes and the KNIME R Binaries and could run the model (as Lars described).
When I then used this R instance (that now had all required libraries installed) as the R instance to be used by FSK-Lab I had to manually install Rserve and miniCRAN. After doing that, the model run through even in FSK-Runner.
So imho there is a conflict between Rserve /miniCRAN and the doParallel packages.
If the doParallel is installed before Rserve /miniCRAN FSK-Lab works. So maybe the easiest "fix" for now is to include doParallel into the packages that are automatically installed - before Rserve and miniCRAN - in the R distributions we provide on our update site.

**Comment by miguelalba** [comment]
The workers spawned by foreach are not configured and do not have the location of the packages. This location could be set for every worker like in https://stackoverflow.com/a/52283502.

Another approach is to configure the libPaths in an startup file like .RProfile or .Renviron but this would affect every R running on a machine. https://csgillespie.github.io/efficientR/3-3-r-startup.html#renviron
