### ISSUE TITLE
Credentials option in FSK file reader possible?

### ISSUE THREAD

**Issue by llavall** [SiLeBAT/FSK-Lab#320]
Hi, I realised that I would like to have the option to enter the login credentials inside of the FSK-Reader like possible for other KNIME nodes (e.g. GET node). If there is an easy way to implement that in the next build, I would appreciate that.

The reason behind that is that I like to use the REST download option inside the FSKX-Reader, but for files stored for example on our KNIME Server I need to enter the login credentials somewhere or use other nodes to first get the file, store it and so on. With my idea it would be more straight forward.

Please let me know what you think about. Might be a great feature for other users as well.

**Comment by miguelalba** [comment]
I disagree. The reader is designed to open local files or public remote ones. Opening files using authentication is a rare use case and would clutter the UI and make it more complicated for the average user.

I would recommend to user other nodes. You could use a REST node to retrieve the file, store it in a temporary file and read it with the FSKX Reader. These nodes could even be reused with a share metanode.
