### ISSUE TITLE
FSKX Writer node seems not to completely fail if error occurs

### ISSUE THREAD

**Issue by llavall** [SiLeBAT/FSK-Lab#322]
In order to use the catch-error node to monitor the failing FSKX Writer, I need to see the behavior of blocking the node outputs. This is missing in the Writer node. Please see attched screenshot.

![FSKX_WriterErrorError](https://user-images.githubusercontent.com/25248947/54513037-627ec100-4956-11e9-9106-ef11595d6231.JPG)

**Comment by ahmadswaid** [comment]
@llavall : Could you please provide us with a simple workflow to reproduce the behavior

**Comment by llavall** [comment]
all you need is a failing writer node and then you check the flow variable port. the picture in the first post shows you the differences in the writer to any other node.

**Comment by mfilter** [comment]
@llavall : I agree. It would have been helpful to have an example workflow.
@ahmadswaid: I think what is requested here is that in cases where the FSKX Writer node fails (for whatever reason) the flow variable port is also switched into "error state". In this way one can test the status of a node that has no output ports. HTH

**Comment by llavall** [comment]
the ticket here is from 2019 - I did open a new one recently to adress the latest findings for the runner node - but all node should show the expected behavior: https://github.com/RakipInitiative/ModelRepository/issues/318

**Comment by llavall** [comment]
Fixed
