### ISSUE TITLE
Editor node removes first simulation scenario if not defaultSimulation

### ISSUE THREAD

**Issue by llavall** [SiLeBAT/FSK-Lab#324]
Tasja found this behavior and I just reproduced it. Please check the attached workflow.

**Comment by ahmadswaid** [comment]
Could you please attach the workflow.

**Comment by llavall** [comment]
sorry, github didn't like the knwf filetype

[bug_removes_first_setting.zip](https://github.com/SiLeBAT/FSK-Lab/files/3068509/bug_removes_first_setting.zip)
