### ISSUE TITLE
Editor JS: caption missing

### ISSUE THREAD

**Issue by schuelet** [SiLeBAT/FSK-Lab#342]
Description for several fields still missing.

They are missing for example for all the properties in the add creator dialog. We need to list all the properties that are missing captions.

![image](https://user-images.githubusercontent.com/19906968/63431521-47414180-c41f-11e9-902a-6177f4335079.png)

**Comment by miguelalba** [comment]
All the properties in the add creator dialog are lacking captions:

- [ ] Title
- [ ] Family name
- [ ] Given name
- [ ] Email
- [ ] Telephone
- [ ] Street address
- [ ] Country
- [ ] Zip code
- [ ] Region
- [ ] Time zone
- [ ] Gender
- [ ] Note
