### ISSUE TITLE
Editor JS: wrong caption in Model Equation

### ISSUE THREAD

**Issue by schuelet** [SiLeBAT/FSK-Lab#344]
Model Math > Model Equation  > Model Equation (field) : wrong caption (ref. Esther 23.)
> 23.	I should do a pointer. How do I do it? I would like more information

![image](https://user-images.githubusercontent.com/19906968/63432209-077b5980-c421-11e9-8d3d-1814dbfccc6d.png)

**Comment by miguelalba** [comment]
This is not a problem in FSK-Lab but in the original metadata spreadsheet. The caption in FSK-Lab is taken as it is from [there](https://docs.google.com/spreadsheets/d/1R5ofJAIqAywN97cnBY9R9kqj10AvQOs3Gq472n6iDyc/edit#gid=811823962).

> The pointer to the file that holds the software code (e.g. R-script)

We should suggest a better explanation of the model equation / script and update FSK-Lab accordingly.

**Comment by schuelet** [comment]
issue no longer appearing. Closing this.
