### ISSUE TITLE
Editor JS: caption and “is a required property” overlap

### ISSUE THREAD

**Issue by schuelet** [SiLeBAT/FSK-Lab#345]
Caption and “is a required property” can overlap. (ref. Esther 26.)

>26.	I cannot see the explanation. It only tells me that it is missing

![image](https://user-images.githubusercontent.com/19906968/63432102-b79c9280-c420-11e9-9dcb-4d20ee2eb973.png)

**Comment by miguelalba** [comment]
We can just replace the caption with tooltips.
