### ISSUE TITLE
Editor JS: title of "Study" has wrong color

### ISSUE THREAD

**Issue by schuelet** [SiLeBAT/FSK-Lab#350]
Data Background > Study : color of “Study*” field should be colored red to indicate mandatory nature 

# Esther's 
> Why does “Study” has an asterisk, although only some information within this section are mandatory
![image](https://user-images.githubusercontent.com/19906968/63433888-4ced5600-c424-11e9-9dcc-e3c3e7b71539.png)

**Comment by miguelalba** [comment]
Well, this is not a bug but more of a design decision. First, the Study* to be colored red is part of the navigation pane and all the entries there have the same style. If not mistaken, only the mandatory missing fields are colored red.

I would leave this issue for later and discuss it here further.
