### ISSUE TITLE
Editor JS: some fields are not self-explanatory

### ISSUE THREAD

**Issue by schuelet** [SiLeBAT/FSK-Lab#352]
There should be tooltips at least for non- self-explanatory field names (ref. Esther 12., 24.)
[Esti.docx](https://github.com/SiLeBAT/FSK-Lab/files/3492354/Esti.docx)
[Esther.docx](https://github.com/SiLeBAT/FSK-Lab/files/3492355/Esther.docx)

**Comment by miguelalba** [comment]
This is the same bug as in #342. Here Esther is reporting on the fields *Basic process* and *Model Equation* not being self-explanatory and lacking a tooltip. But these are not the only fields missing tooltips.

I would not close this yet or mark it as duplicated. But it will be closed with #342.
