### ISSUE TITLE
Editor JS: quotation marks in model equation class

### ISSUE THREAD

**Issue by schuelet** [SiLeBAT/FSK-Lab#354]
Model Math > Model Equation > Model Equation Class: quotation marks of some classes need to be removed (ref. Esther 21.)
[Esther.docx](https://github.com/SiLeBAT/FSK-Lab/files/3492369/Esther.docx)
[Esti.docx](https://github.com/SiLeBAT/FSK-Lab/files/3492370/Esti.docx)

**Comment by miguelalba** [comment]
This is not a problem with FSK-Lab but the controlled vocabularies where these values are taken from.
