### ISSUE TITLE
Editor JS: views have "modal header" instad of title

### ISSUE THREAD

**Issue by schuelet** [SiLeBAT/FSK-Lab#355]
Some views have “modal header” instead of an actual title

> Why is the section called “Model Equation” and the headline of the window is “Modal header” (that issues arises in multiple sections) 
![image](https://user-images.githubusercontent.com/19906968/63436030-4365ed00-c428-11e9-96b5-6edb68693f4a.png)

**Comment by miguelalba** [comment]
Fixed in new GUI: a50decf35eecb8a6885b9b26b3ca2946d69e1fee
