### ISSUE TITLE
Editor JS: parameter data types difficult to read

### ISSUE THREAD

**Issue by schuelet** [SiLeBAT/FSK-Lab#356]
Model Math > Parameter > Data Type: some types are in all caps and difficult to read.

> The options are not very pleasing to read. What about VectorOfStrings?
![image](https://user-images.githubusercontent.com/19906968/63437820-95f4d880-c42b-11e9-81ce-4256ff7d5bef.png)

**Comment by miguelalba** [comment]
Closed with new editor
