### ISSUE TITLE
Editor JS: status for references should be controlled vocabularies

### ISSUE THREAD

**Issue by schuelet** [SiLeBAT/FSK-Lab#358]
General Information>Reference>Status: provide a drop down list of acceptable status options (“published”, “submitted”, etc.) (ref. Esther 9.)

> 9.	Suggestion: The status of a paper is only a limited number of options. It would be nice if that would be a list (as it is the case for units)
![image](https://user-images.githubusercontent.com/19906968/63438145-2501f080-c42c-11e9-897b-f1ff5011b5ad.png)

**Comment by miguelalba** [comment]
Fixed in new GUI: a50decf35eecb8a6885b9b26b3ca2946d69e1fee
