### ISSUE TITLE
Editor JS: drop down menu for Unit not working

### ISSUE THREAD

**Issue by schuelet** [SiLeBAT/FSK-Lab#359]
Scope > Hazard > Unit  does not have a drop down menu (ref. Esther 18.)

> Here the unit cannot be chosen from a list
![image](https://user-images.githubusercontent.com/19906968/63437993-e704cc80-c42b-11e9-93f0-cc27a900a1f2.png)

**Comment by miguelalba** [comment]
Fixed in new GUI: a50decf35eecb8a6885b9b26b3ca2946d69e1fee
