### ISSUE TITLE
Editor JS: mandatory fields are not enforced

### ISSUE THREAD

**Issue by schuelet** [SiLeBAT/FSK-Lab#360]
mandatory fields are not enforced (ref. Esti 5.)

> In Model Math tab if I add a new parameter and I do not complete all the required fields, I see the warning indicating how many required properties are missing, but if I close the node and save the changes no error is shown. Actually I can still run the model but if then I try to use the FSKX Writer node I get this error: Execute failed: (“Null pointer exception”): null. I remember that in previous versions it used to show on the bottom of the Editor node a warning saying that something was wrong when some information was missing.

![image](https://user-images.githubusercontent.com/19906968/63446504-9e084480-c43a-11e9-897c-832a9d01d313.png)

**Comment by schuelet** [comment]
This is still the case and I suggest we keep it simple and try to add a warning if so-called mandatory fields are not filled out. Saving the editor should always be possible, in case someone wants to continue working on it later.

**Comment by mfilter** [comment]
agree

**Comment by schuelet** [comment]
@ahmadswaid : java script side: 
- window pop up if user wants to close editor with missing mandatory fields. Window includes all information about missing poperties.
- transfer information to java side (or prepare transfer)

@miguelalba 
- get warning messages from javascript to java side
- warning (node) if editor is saved with missing mandatory fields
-

**Comment by schuelet** [comment]
fixed as of https://app.zenhub.com/workspace/o/silebat/fsk-lab/issues/849
