### ISSUE TITLE
Editor JS: several fields in Exposure are missing

### ISSUE THREAD

**Issue by schuelet** [SiLeBAT/FSK-Lab#364]
Model Math > Exposure is incomplete for Generic Model

![image](https://user-images.githubusercontent.com/19906968/63446738-05be8f80-c43b-11e9-8d80-684dd6a02379.png)

**Comment by miguelalba** [comment]
Fixed in new GUI: a50decf35eecb8a6885b9b26b3ca2946d69e1fee
