### ISSUE TITLE
Editor JS: "+" button not working

### ISSUE THREAD

**Issue by schuelet** [SiLeBAT/FSK-Lab#365]
Model Math > Exposure: “+” button is not working for Dose-Response Model (ref. Esther 17.)

[Esther.docx](https://github.com/SiLeBAT/FSK-Lab/files/3492522/Esther.docx)
[Esti.docx](https://github.com/SiLeBAT/FSK-Lab/files/3492523/Esti.docx)

**Comment by miguelalba** [comment]
Fixed in new GUI: a50decf35eecb8a6885b9b26b3ca2946d69e1fee
