### ISSUE TITLE
Editor JS: "+" button locks view

### ISSUE THREAD

**Issue by schuelet** [SiLeBAT/FSK-Lab#366]
Clicking on “+” button in Model Math > Model Equation: adding reference to model equation has no assigned method and locks the view permanently (ref. Esther 19.)
[Esther.docx](https://github.com/SiLeBAT/FSK-Lab/files/3492537/Esther.docx)
[Esti.docx](https://github.com/SiLeBAT/FSK-Lab/files/3492538/Esti.docx)

**Comment by miguelalba** [comment]
Fixed in new GUI: a50decf35eecb8a6885b9b26b3ca2946d69e1fee
