### ISSUE TITLE
readme text not wrapped

### ISSUE THREAD

**Issue by schuelet** [SiLeBAT/FSK-Lab#373]
The readme text in the object wrapper and the editor js view is has no line breaks, so in order to read it, you need to scroll to the left.
We need to implement an auto line - break or auto word wrap to make it more easily readable.

**Comment by miguelalba** [comment]
If I understand correctly you want to replace the scroll bars with wrapped text?

Currently we are using scroll panes in the FskPortObject view and the Editor JS view.
![image](https://user-images.githubusercontent.com/19906968/64695266-02e41700-d49c-11e9-99df-11420ac39cea.png)

![image](https://user-images.githubusercontent.com/19906968/64695303-13948d00-d49c-11e9-95b5-aab2fd1d2182.png)
