### ISSUE TITLE
Tooltip of is reference exceeds windows size

### ISSUE THREAD

**Issue by miguelalba** [SiLeBAT/FSK-Lab#406]
The tooltip of the "Is reference" property in the reference dialog of the editor node overflows the window and part of the tooltip is not visible.
![image](https://user-images.githubusercontent.com/19906968/79469899-0a0a6f00-8001-11ea-99ec-87d777bed399.png)

**Comment by schuelet** [comment]
There are no tooltips anymore after the new UI was implemented. But most fields have an Info with some description. For is_Reference, there is no description

**Comment by mfilter** [comment]
this is available now.
