### ISSUE TITLE
simulation configurator: Constant values

### ISSUE THREAD

**Issue by schuelet** [SiLeBAT/FSK-Lab#416]
it appears, that constant parameters can be modified right now. Those parameters should be grayed out in the view![Screenshot from 2020-05-06 11-45-52.png](https://images.zenhubusercontent.com/5e4ba30f8f780f7f48f8f306/5fe8ba16-ecd0-45d7-875f-8a933c37c91e)

**Comment by miguelalba** [comment]
The problem is in JSSimulatorNodeModel toJSSimulation method. The filter is returning any non output parameter. This filter should be changed to only output input parameters. https://github.com/SiLeBAT/FSK-Lab/blob/c2949e37923a8d18312a01379f202b90b10c29c3/de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/nodes/JSSimulatorNodeModel.java#L272

**Comment by schuelet** [comment]
I remember Matthias saying, he wants to see the constant parameters. The user should just not be able to change them. Isn't that something we need to fix in the JS code?

**Comment by mfilter** [comment]
No, actually I'm fine if constant parameters are not displayed in the simulation config view, as the user is not supposed to change them.
HTH

**Comment by schuelet** [comment]
I made constant parameters readonly. Matthias specifically wanted to be able to see them in the config view, I had to do it back in the day of pmm -> fsk conversion. 

Also, that used to be the way we did it before you took it out. 

I hope it is alright with you.

**Comment by schuelet** [comment]
I also want to add that maybe some modeller needs to see the constant parameters to understand what is going on, since they too can have relevant metadata.

I think it is fine if they are visible but grayed out. (see me eat my words in a bit when everybody complains about them)

**Comment by schuelet** [comment]
OK I change it back and remove them from the view. Sorry I thought I was talking to Miguel. My bad.

**Comment by schuelet** [comment]
I tested it with Miguel's suggestion but it has ramifications:
- all generated simulations are now incomplete (i.e. no constant parameters at all ) since the generated simulation for the outport is taken from the view value.

We can make the constant parameters invisible (hidden) but I honestly like the grayed out version better, since then the user can get some meta information from them. 

I leave it for now and we see how it ends.

**Comment by mfilter** [comment]
I'm also fine with a solution where the constant values are shown and are greyed out. Some user might see this as a very nice feature, others might be confused. Do whatever creates the least effort for you
HTH

**Comment by schuelet** [comment]
Very good. Then we consider this issue solved for now.
