### ISSUE TITLE
Errors when visualization script contains multiple lines or ggplot

### ISSUE THREAD

**Issue by Fusiakja** [SiLeBAT/FSK-Lab#422]
Following error occurs in FSK Lab when trying to run a model when the visualization script contains multiple lines/plots or ggplot: 

> Execute failed: Invalid result. Execution failed. Reason: Incorrect implementation; the execute method in RunnerNodeModel returned null or an incorrect number of output tables.

To Reproduce:

[working FSKX](https://firebasestorage.googleapis.com/v0/b/test-cb8b2.appspot.com/o/0yvapvkjs4w%2Fworking.fskx?alt=media&token=ba323f0b-7e90-4c0e-aa6f-1ce2163a74d8)
[not working FSKX](https://firebasestorage.googleapis.com/v0/b/test-cb8b2.appspot.com/o/0yvapvkjs4w%2Fnot_working.fskx?alt=media&token=a320a2df-041c-45b3-af02-624de705ac37)

Using KNIME version: 3.7.2
Using FSK Lab version: 1.7.2.201912161607

Does anyone know why this happens?

**Comment by mfilter** [comment]
I assume it's because FSK-ML defines that there can only be 1 visualization plot.
HTH,
MF

**Comment by schuelet** [comment]
Since the behavior of FSK-Lab is not at fault here, I close this ticket.
There is another ticket that considers multiple plots (#56).
