### ISSUE TITLE
editor js data not recoverable

### ISSUE THREAD

**Issue by schuelet** [SiLeBAT/FSK-Lab#425]
- deserialization issue when editor loses input port object:
![image](https://user-images.githubusercontent.com/38949263/82905168-cee64e80-9f63-11ea-931a-ecb8718baf8c.png)

- saving and loading wf: editor with older metadata (still saved as string, see #412) not recoverable
  - see file attached
[FSK_TertiaryModel_with_Joiner.zip](https://github.com/SiLeBAT/FSK-Lab/files/4682481/FSK_TertiaryModel_with_Joiner.zip)

ERROR FSK Editor JS        2:5         at [Source: java.io.StringReader@52774909; line: 1, column: 1]
com.fasterxml.jackson.databind.JsonMappingException: Can not construct instance of de.bund.bfr.metadata.swagger.GenericModel: no String-argument constructor/factory method to deserialize from String value ('"\"\\\"\\\\\\\"\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"{\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
....

**Comment by schuelet** [comment]
Here are the models as fskx files for to help with debugging.
[models.zip](https://github.com/SiLeBAT/FSK-Lab/files/4682666/models.zip)

**Comment by miguelalba** [comment]
Fixed in 7facb140bdbbc6bba360300bab946e0432094367
