### ISSUE TITLE
Explore JEP

### ISSUE THREAD

**Issue by miguelalba** [SiLeBAT/FSK-Lab#429]
Explore the Python integration with [JEP](https://github.com/ninia/jep) in a KNIME SDK setup environment.

> Jep embeds CPython in Java through JNI.
> 
> Some benefits of embedding CPython in a JVM:
> 
>     Using the native Python interpreter may be much faster than alternatives.
>     Python is mature, well supported, and well documented.
>     Access to high quality Python modules, both native CPython extensions and Python-based.
>     Compilers and assorted Python tools are as mature as the language.
>     Python is an interpreted language, enabling scripting of established Java code without requiring recompilation.
>     Both Java and Python are cross platform, enabling deployment to different operating systems.

**Comment by schuelet** [comment]
JEP has the same or similar constraints as Renjin does: It doesn't fully support packages. The KNIME python integration is quite robust and fast, so we will drop this idea for now.

Might still be interesting further down the line, so I put it on ice.
