### ISSUE TITLE
NPE in runner connected to reader

### ISSUE THREAD

**Issue by miguelalba** [SiLeBAT/FSK-Lab#443]
Reported by MF. NPE returned by runner connected to reader.

Not reproduced. Might be related to missing working directory when KNIME is reopened and the temporary directory used as working directory is gone. Another cause could be corrupted ~/.fsk folder.

![Unbenannt](https://user-images.githubusercontent.com/19906968/86486197-f8f91080-bd5a-11ea-9ba6-9a9f78c25f5f.png)

**Comment by schuelet** [comment]
Unfortunately there are not enough information about this issue. @mfilter If you still have this testCampy folder we can have a look, otherwise I close this ticket.

**Comment by mfilter** [comment]
seems to work now.
