### ISSUE TITLE
Esther Joiner 1: Joiner doesn't work if no Joining took place

### ISSUE THREAD

**Issue by schuelet** [SiLeBAT/FSK-Lab#472]
- make sure, that the joiner works, even if no connections where drawn

**Comment by schuelet** [comment]
issue not reproducable

**Comment by schuelet** [comment]
As of FSK-Lab 2.0 this is only happening if a Joiner is simply executed without opening the View once. The models don't actually need a connection, but the View needs to be opened. 
@ahmadswaid Do you think this is worthwhile

[https://app.zenhub.com/files/73478810/570a0054-6a8c-4fca-9781-8a1cf6475f8e/download](https://app.zenhub.com/files/73478810/570a0054-6a8c-4fca-9781-8a1cf6475f8e/download)?

**Comment by mfilter** [comment]
a "joining" of models without opening the view should work even if the models are not graphically connected

**Comment by llavall** [comment]
May I ask what the intention behind a joining without joining is? KNIME often blocks execution of a node if there is no setting done before.  If the joiner should be allowed to run without a connection inside it should at least give a warning that there was no actual joining set up.

**Comment by mfilter** [comment]
This is a desired feature to simply get two models executed in the same R workspace. A warning would of course not harm, but this was not the issue reported here.

**Comment by mfilter** [comment]
at least for me the Joiner works, but the Runner creates a NPE.
knime://BfR-extern/FSKX_Testing/FSK-Lab_2.0/broken_workflows/20210412_Test_JoinerWithoutGraphicalJoining_MF

**Comment by schuelet** [comment]
fixed as of https://app.zenhub.com/workspace/o/silebat/fsk-lab/issues/854
