### ISSUE TITLE
Esther Joiner 8: make connections possible from input (1) to output (2)

### ISSUE THREAD

**Issue by schuelet** [SiLeBAT/FSK-Lab#474]

**Comment by schuelet** [comment]
I put this on hold, since I am not sure if this is reasonable: First, the input parameter value could change over the course of the model script. Second, the output parameter is generated by the model.
To make this work, we need to save the input before running the model script, then we need to overwrite the output parameter.

**Comment by mfilter** [comment]
will not be done
