### ISSUE TITLE
Esti Editor 18: Parameter Tooltip should also say that constant parameters require value 

### ISSUE THREAD

**Issue by schuelet** [SiLeBAT/FSK-Lab#487]

**Comment by mfilter** [comment]
This links to the info button within the "Add Parameter" pop up window of the Editor node. There the description for the input field "Value" should be changed to "A default value for the parameter. This is mandatory (needs to be provided) for all parameters of type 'Input' and "Constant""
@miguelalba : this needs to be updated in the new metadata schema as well.

**Comment by schuelet** [comment]
fixed as of https://app.zenhub.com/workspace/o/silebat/fsk-lab/issues/850
