### ISSUE TITLE
writer saves plot as png

### ISSUE THREAD

**Issue by schuelet** [SiLeBAT/FSK-Lab#493]
The writer saves the plot as "plot.png", even if the file is an .svg.

![writer_save_png_bug](https://user-images.githubusercontent.com/38949263/88910318-9eb97580-d25c-11ea-913a-71f1dfc0ab0b.PNG)

**Comment by miguelalba** [comment]
In de.bund.bfr.knime.fsklab.v2_0.writer.WriterNodeModel at line 264:
`// TODO: THIS DOES NOT WORK IN WINDOWS: png file cant be opened without renaming the file to .svg`

If I remember correctly the generated plot is an SVG file so it would make sense that it could not be opened as PNG. From ScriptHandler#runSnippet:
`plotter.plotSvg(imageFile, fskObj.getViz());`.

The rest of WriterNodeModel is using a hardcoded PNG uri. It should be SVG.

**Comment by schuelet** [comment]
fixed in https://github.com/SiLeBAT/FSK-Lab/pull/852
