### ISSUE TITLE
Support combined models in the FSK-Editor

### ISSUE THREAD

**Issue by schuelet** [SiLeBAT/FSK-Lab#503]
The editor shows the metadata of the model, including the script and (ideally) the uses resource files. But that is only implemented for single models.
Combined models consist of multiple models (which can be combined models as well).

- minimum Goal: 
  - Editor allows annotation of combined model (related to #200)

- nice to have (low priority):
  - tree structure of model is visible
  - individual models are selectible
  - metadata of selected model can be accessed
  - model scripts of selected model can be accessed

**Comment by mfilter** [comment]
please check if this can be closed

**Comment by schuelet** [comment]
@mfilter The minimum goal (see above) is achieved. Since the Joiner Component allows alteration of the individual models before Joining, we at least have a way to do everything we want even if it is a bit convoluted.
I don't know what happens if one tries to join and edit combined models though, we don't have any of them in the repository. I will open a ticket to investigate this use case.
