### ISSUE TITLE
Reader can load icpmf Combined models in version 1.8.1.+

### ISSUE THREAD

**Issue by schuelet** [SiLeBAT/FSK-Lab#510]
Combined models created with a version prior to 1.8.1. can not be read and executed on later FSK-Lab versions due to the extensive changes that have been made.

Solution: The join relations of a joined model (icpmf) have hopefully all the information needed for the conversion to make that model executable in FSK-Lab 1.8.1.+ .

Nice to have: 
Throw a warning, that the fskx model was made with an old version when using FSK-Lab 1.8.1.+ .

**Comment by miguelalba** [comment]
- [ ]

**Comment by schuelet** [comment]
ready for testing: https://dl.bintray.com/silebat/development

**Comment by miguelalba** [comment]
@Thatsreallycool and @ganasp this ticket is solved in the release candidate 2 for 1.9.0 at https://dl.bintray.com/fsk/1.9.0-rc2. Please test and mark this ticket as done if it works for you. Thanks.

**Comment by ganasp** [comment]
testing https://dl.bintray.com/fsk/1.9.0-rc2/ with combined_icpmf.fskx models
Models could be read (FSKX Reader) and executed (FSK Runner) successfully!
