### ISSUE TITLE
Restore ICPMF nodes as deprecated nodes

### ISSUE THREAD

**Issue by miguelalba** [SiLeBAT/FSK-Lab#558]
The nodes in the current ICPMF update site with release 1.7.2 from the commit 2d1c688 from 21st Nov 2019 should be included as deprecated in the project _de.bund.bfr.knime.fsklab.deprecatednodes_. This includes:

| Node | Factory |
| ----- | -------- |
| Creator | de.bund.bfr.knime.fsklab.nodes.CreatorNodeFactory |
| Runner | de.bund.bfr.knime.fsklab.nodes.RunnerNodeFactory |
| Fsk to R | de.bund.bfr.knime.fsklab.nodes.FskToRNodeFactory |
| Reader | de.bund.bfr.knime.fsklab.nodes.ReaderNodeFactory |
| Writer | de.bund.bfr.knime.fsklab.nodes.WriterNodeFactory |
| FSK to metadata | de.bund.bfr.knime.fsklab.nodes.FSK2MetadataNodeFactory |
| Simulation configurator | de.bund.bfr.knime.fsklab.nodes.JSSimulatorNodeFactory |
| Joiner | de.bund.bfr.knime.fsklab.nodes.JoinerNodeFactory |
| Editor | de.bund.bfr.knime.fsklab.nodes.FSKEditorJSNodeFactory |

Besides and before porting these nodes, it is required for most of these to migrate first their port object in the project de.bund.bfr.knime.fsklab.type. These classes can be just included in a package inside the deprecated nodes project. In the package *de.bund.bfr.knime.fsklab*:
- CombinedFskPortObject
- CombinedFskPortObjectSpec
- FskPortObject
- FskPortObjectSpec
- FskSimulation
- JoinRelation

**Comment by schuelet** [comment]
UPDATE SITE: [https://dl.bintray.com/fsk/1.9.0-rc1](https://dl.bintray.com/fsk/1.9.0-rc1)

**Comment by schuelet** [comment]
update site release candidate: [https://dl.bintray.com/fsk/1.9.0-rc1](https://dl.bintray.com/fsk/1.9.0-rc1)

**Comment by schuelet** [comment]
Testing available at: https://dl.bintray.com/silebat/development

Test Workflow: 

[https://app.zenhub.com/files/73478810/77403f9f-2803-480d-98c4-4b212e5fee8a/download](https://app.zenhub.com/files/73478810/77403f9f-2803-480d-98c4-4b212e5fee8a/download)

**Comment by schuelet** [comment]
#141: create feature for deprecated nodes

**Comment by schuelet** [comment]
FSK-Lab built on KNIME 4 platform: [https://dl.bintray.com/fsk/2.0.0-rc1](https://dl.bintray.com/fsk/2.0.0-rc1)
(TODO: change version number to 2.0)

FSK-Lab last version for icpmf (KNIME 3.7): [https://dl.bintray.com/fsk/1.9.0-rc3](https://dl.bintray.com/fsk/1.9.0-rc3)
