### ISSUE TITLE
simulation index always on default in Simulation Configurator when loading a workflow

### ISSUE THREAD

**Issue by schuelet** [SiLeBAT/FSK-Lab#632]
After loading a workflow with a Simulation Configurator, the default simulation is always selected. This applies only to the JS View, as the portObject still has the correct simulation index selected.

**Comment by ganasp** [comment]
testing https://dl.bintray.com/fsk/1.9.0-rc2/
Workflow containing FSKX Reader->FSK Simulation Configurator JS -> FSK Runner
Build up workflow and selecting a simulation different from defaultSimulation (FSK Simulation Configurator: close & apply), saving workflow, reloading workflow
after reloading the workflow: interactive view of FSK Simulation Configurator showed defaultSimulation, but Runner used the before selected simulation
after reloading the workflow and reset of all nodes: execute FSKX Reader followed by execute and open views for FSK Simulation Configurator, now selected simulation was shown, NOT the defaultSimulation, FSK Runner used this selected simulation

**Comment by schuelet** [comment]
#632 was fixed in release candidate 3 (https://dl.bintray.com/fsk/1.9.0-rc3/ )

**Comment by ganasp** [comment]
testing https://dl.bintray.com/fsk/1.9.0-rc3/
Build up workflow and selecting a simulation different from defaultSimulation (FSK Simulation Configurator: close & apply), saving workflow, reloading workflow
after reloading the workflow: interactive view of FSK Simulation Configurator showed the before selected simulation, NOT defaultSimulation
