### ISSUE TITLE
Reader Node fails if the same file is read by another Reader at the same time

### ISSUE THREAD

**Issue by schuelet** [SiLeBAT/FSK-Lab#634]
When the first reader opens the file to read it, any other reader trying the same will not be able to get access and fail.

**Comment by mfilter** [comment]
please update this ticket.

**Comment by schuelet** [comment]
@miguelalba if I recall correctly, the short term solution was to make a copy of the file before opening the combine archive. We also discussed a way to have the Reader wait if an archive is currently being opened i.e. blocked. How should we proceed?

**Comment by schuelet** [comment]
issue was solved in https://github.com/SiLeBAT/FSK-Lab/pull/895
