### ISSUE TITLE
Reader fails when reading a model that doesn't have an entry in "languageWrittenIn" 

### ISSUE THREAD

**Issue by schuelet** [SiLeBAT/FSK-Lab#635]
easily solved by using the method defaultString from StringUtils

add to ReaderNodeModel.java line 456: 
String languageWrittenIn = StringUtils.defaultString(SwaggerUtil.getLanguageWrittenIn(model), "r");

**Comment by ganasp** [comment]
testing https://dl.bintray.com/fsk/1.9.0-rc2/
FSKX Reader is able to read fskx model which doesn't have an entry for LanguageWrittenIn
