### ISSUE TITLE
Create endpoint for conversion microservice

### ISSUE THREAD

**Issue by schuelet** [SiLeBAT/FSK-Lab#636]
Only define the API but leave the call empty or return an empty model of the target model class.

See NodeUtils#initializeModel

**Comment by miguelalba** [comment]
[Continues] An algorithm must be implemented and exposed in the internal service so that it can be used in JS views.
- Inputs: original model metadata and target model class
- Output: converted model metadata

**Comment by mfilter** [comment]
@miguelalba : please update the status

**Comment by schuelet** [comment]
Conversion is implemented.
