### ISSUE TITLE
Extract models metadata as a JSON list in the case of local repository

### ISSUE THREAD

**Issue by ahmadswaid** [SiLeBAT/FSK-Lab#642]
There are two options:
1- Redesign the code of reading the FSKX file as a FSK Object in the FSK reader, extracting it as a public method in a separated class.
    and in this case call this method from the FSKDBVIew Node to collect the Metadata JSON list.
2- Use KNIME nodes to extract them like the solution provided by Lars in FSK web.

**Comment by miguelalba** [comment]
I do not remember much of the local repository approach and where the metadata is actually read. If understand it right, you need an array of the metadata of all the models in a local repository.

Do you need to load the individual metadata of all the models combined in a joined model? If so, there is not other option but using the reader code. If not, you could go with **option 2** and use the reader in a loop. The reader node has received updates and is much leaner, so it does not create working directories, download packages or does anything other than reading the data in the files. You could use it next to an FSK to metadata node to extract the metadata but this would only work with simple models or metadata of joined models. This approach would also need to manually aggregate the metadata as the FSK to metadata node splits it into four components: general information, scope, data background and model math.

For **option 1**, do you need anything other than the metadata?

**Comment by ahmadswaid** [comment]
I will go with option 2 and yes, we will need the model script and visualization script for the editor later on.
it's possible to use both the reader with fsk2metadata node to extract the metadata but not possible to get the other resources with this way
I was planing to use some Knime node to extract these resources from the FSKX file
![Screen Shot 2020-09-25 at 12.03.27 PM.png](https://images.zenhubusercontent.com/5f5ceabffa83aa3609e2d209/1f8a3791-8197-4683-be14-cf6fce4260cf)
