### ISSUE TITLE
Creating the FSK DB View Dialog

### ISSUE THREAD

**Issue by ahmadswaid** [SiLeBAT/FSK-Lab#645]
The setting should enable the end use to provide the location to the repository.
By default, the repository location should reference:
https://knime.bfr.berlin/backend/metadata

**Comment by miguelalba** [comment]
I am bit confused here. If I get it right, the FSK DB View will have a configuration dialog allowing the user to pick a repository. And in the node settings, if not configured the metadata of the landing page will be used.

I think we could split this issue in two. One for the dialog and another for the node settings. For this node, we should consider what other configuration values we might include, like selected model index, etc. Also, not all the settings will be copied as default in the JS view. For your example the selected model will be copied from the JS view but the repository location will not.

**Comment by miguelalba** [comment]
PR: https://github.com/SiLeBAT/FSK-Lab/pull/684

**Comment by miguelalba** [comment]
@mfilter and @llavall this is a more technical ticket where the nodes is not finished yet but only some parts. Does it make sense for you to test the dialog or should a developer test it and close it? I would still argue for a complete testing of the node once finished.

**Comment by mfilter** [comment]
it's enough if you test it. I will test the epic to which this is linked.

**Comment by miguelalba** [comment]
It is working for me.
