### ISSUE TITLE
Converting knime table into JSON Array for FSK DB View

### ISSUE THREAD

**Issue by ahmadswaid** [SiLeBAT/FSK-Lab#646]
Add the business logic for converting knime table into JSON Array and deliver it to the JS view of FSK DB View Node

**Comment by miguelalba** [comment]
What is the input KNIME table? How does it look like? What is the spec, columns, types, etc.? If it is described in another issue or resource please link it.

**Comment by ahmadswaid** [comment]
The input Port of this node will be of org.knime.core.node.BufferedDataTable.
This received table should be converted to proper form for the JS View, This could be a org.knime.js.core.JSONDataTable.
Each row of this table should contains the model metadata in addition to the model, vis script all as String.
