### ISSUE TITLE
Four optional Input port for the joiner

### ISSUE THREAD

**Issue by ahmadswaid** [SiLeBAT/FSK-Lab#648]
Redesign the Joiner to have four optional input ports.
this will has an effect on the logic on both JS and back end part of the node.
the node should not fail to open the JS view if no model is provided via the input ports (minimum two) but should give a warning if no model is provided via the knimeservice selection event to the joiner JS view and that warning should be raised on the java back end part.

**Comment by mfilter** [comment]
not sure if "fail if no model is provided via the knimeservice selection event" is correct. Assuming the new joiner is used inside a component and by chance the user deselect all models in the DB view, then I would not expect that the joiner exit with an error.
Maybe it's better to state, the joiner should only become executable if at least two models are provided at the inports or two selection events were triggered.

**Comment by ahmadswaid** [comment]
The node should be executable in any case since we will make the input port optional.
what will happen if the node executed and no models provided in the end. what is the combined object in this case , is it null.

**Comment by mfilter** [comment]
my comment related specifically to the section " but should fail if no model is provided via the knimeservice selection event", as this could be misinterpreted. If the node doesn't fail but gives a warning stating" "This node created an empty model port object" similar to the KNIME row filter nodes when an empty table is created this is OK.

**Comment by miguelalba** [comment]
Is the output still an FskPortObject? The problem with this is that we cannot represent an empty or missing model, unlike the KNIME tables that can be empty. We could either extend the port object to represent a MISSING or EMPTY state or the joiner could output an optional port that would needed to be checked for every node connected to it.

**Comment by ahmadswaid** [comment]
I agree with @miguelalba on that and I'm more with the optional output port.
