### ISSUE TITLE
Reorder feature of models in the joiner

### ISSUE THREAD

**Issue by ahmadswaid** [SiLeBAT/FSK-Lab#649]
The user should be able to reorder the models in the JS View of the joiner that means source and target of joining is not predetermined and the user should be able to set any model as the source of the joining connection.
The reordering could be by showing an external popup in the JS View where the order is defined.

**Comment by mfilter** [comment]
this feature has significant implications on the error handling, as one has to avoid circular dependencies of parameters. Therefore it might be better to find a different solution for defining the order of models, e.g. having a dedicated drop-down menu inside the model box, where the user need to select the order from 1 to 4.

**Comment by ahmadswaid** [comment]
The node should be executable in any case since we will make the input port optional. 
what will happen if the node executed and no models provided in the end. what is the combined object in this case , is it null.

**Comment by ahmadswaid** [comment]
I'm not sure if the current joining UI tool does support the proposed way.
But the reordering could be by using external popup where the order is defined. if you agree on that I can change the ticket description

**Comment by mfilter** [comment]
this is complety up to you, how it is implemented.
