### ISSUE TITLE
Remove the editor part in the joiner JS view

### ISSUE THREAD

**Issue by ahmadswaid** [SiLeBAT/FSK-Lab#650]
No edit of joining metadata is possible via the joiner JS view.
this should only be possible using the Editor JS View

**Comment by mfilter** [comment]
Neventheless, the joiner has to provide joined metadata at the outport, that are generated via the metadata conversion endpoint

**Comment by miguelalba** [comment]
We already have a metadata table in the KNIME server that is used in the landing page as well to show metadata but not edit it. It might be helpful. https://github.com/SiLeBAT/knimeserver/tree/master/de.bund.bfr.knimeserver.nodes
