### ISSUE TITLE
Create a workflow for the new Joiner(KNIME component)

### ISSUE THREAD

**Issue by ahmadswaid** [SiLeBAT/FSK-Lab#654]
This should include the FSK DB View, the Joiner and the editor.
In addition to that, add the configuration components which are used to make configuration dialog for the Joiner KNIME Component.

**Comment by mfilter** [comment]
please elaborate a bit on that. It is not clear, what this workflow is good for. For sure we need a workflow for demonstration purpose, but also one or preferably more WFs for the test pipeline

**Comment by ahmadswaid** [comment]
In my understanding, The only way to use the the Knime Component feature is in a workflow.
by creating this workflow we configure and collect the required nodes for building the final joiner component.
this component at the end can be shared and used locally or on the server.

**Comment by mfilter** [comment]
I apparently misunderstood the headline. I thought you plan to create a workflow that has the Joiner Component included as one of the nodes. But if this ticket describes the KNIME workflow that IS the Joiner component that's fine.
