### ISSUE TITLE
Joiner Node Refactoring

### ISSUE THREAD

**Issue by ahmadswaid** [SiLeBAT/FSK-Lab#662]
- The joiner node should be enhanced to accept maximum four models as optional ports if the joiner works as usual out of Knime   component. but will get these models via the Knimeservice (as event bus) if it is used in the knime component.
in both cases the java backend should produce the combined FSK object ready for running or writing.  
- The enhancement will include the ability to reorder the models as source and target of joining.
- The joiner will not be able to edit it metadata and that will be only doable by using the editor.
- The node will be able to recognize that it is working in interactivity environment(Knime component feature) and then get selection event from the FSK DB View or the editor on editing a selected model for joining. 
- The JS View has to produce the combined json metadata with the help of metadata converting endpoint.
- The Joiner can emit edit request event which is received in the editor JS.
- The node dialog should allow the user to  define the simulation merging strategy.

**Comment by mfilter** [comment]
the Joiner node also has to create combined simulation settings for the joined model. It should be defined how this combination is performed. In an ideal solution the user has somewhere the chance to define this, e.g. a) combine just the default simulation scenario from each base model or b) create automatically a combination of all existing simulation scenarios from each base model or c) select individual simulation scenarios from each base model that are then combined.

**Comment by mfilter** [comment]
I suggest to add a dedicated ticket with a list of test workflows that need to be established for this node.

**Comment by mfilter** [comment]
Doesn't this node need to be able to emit an event as well? After the joining is accomplished the newly created joined metadata should become editable in the Joiner component

**Comment by ahmadswaid** [comment]
The Idea proposed on giving the user the option to select the simulation merging strategy looks good but  what will happen if the user chooses the second option of "automatically a combination of all existing simulation scenarios" and each model has a different number of scenarios provided?

**Comment by mfilter** [comment]
then you "multiply" those scenarios, i.e. model A and B have 2 scenarios each then the combined model has 4 scenarios.
