### ISSUE TITLE
Joiner Knime Component Workflow

### ISSUE THREAD

**Issue by ahmadswaid** [SiLeBAT/FSK-Lab#664]
- This workflow will be created to use the Knime Component feature introduced in knime platform 4.1 and after.
- This will use Knime configuration nodes to configure and create dialog for the Component.
- It contains a part reads local FSKx files which is run if the user configure the component to some local repo.
- This component hosts the mainly: FSK DB View, The joiner  and the Editor JS nodes in addition to other utility and configuring nodes.  
- The sub JS Views of the the final Joiner Component can be organized and layout use knime layout tool.

![image.png](https://images.zenhubusercontent.com/5f5ceabffa83aa3609e2d209/1c5e42b9-f448-40e9-af4b-071ce352b5a7)
![Joiner Component.png](https://images.zenhubusercontent.com/5f5ceabffa83aa3609e2d209/666cc787-c554-48fc-b43c-94641ec19c00)
![image.png](https://images.zenhubusercontent.com/5f5ceabffa83aa3609e2d209/0a447d20-7abd-47d8-acad-e360a27240e8)

**Comment by mfilter** [comment]
Please check the spelling in the figures.
I also have the impression that in the 2nd figure a number of "receive notification" boxes are missing.
Specifically explain how it will be guaranteed that the "Joined model produced" step includes all edits from the Editor handling the joined model metadata

**Comment by mfilter** [comment]
Mission accomplished
