### ISSUE TITLE
FSK DB View

### ISSUE THREAD

**Issue by ahmadswaid** [SiLeBAT/FSK-Lab#665]
- This Knime node will provide the functionality of listing the FSK Models in a table view enabling the user to select two to four of them in preparation to join them or edit each one of them using the editor.
- The Node is dependent on some local or online models metadata  repository to provide it with list of JSON Object as an array.
- This node emits event on selection using KnimeService which is responsible for emitting it to  subscribers ( the joiner and the editor modules)
- The node should deliver the received JSON array to a java script module and this one will be used to feed an HTML table with data.
- This Node should define the received metadata JSON Array as a global window variable to play the role of shared repository between it, the Joiner and the Editor.
- The node will output the models as a Knime table along with its selection status.
- The node configuration dialog should define: the max number of possible model selection and repository location as node configuration and these fields should be possible to be managed by flow variable along with Knime configuration nodes.

![image.png](https://images.zenhubusercontent.com/5f5ceabffa83aa3609e2d209/10042e86-c295-45e9-bcc4-200910b7b7ff)

**Comment by ahmadswaid** [comment]
- This Knime node will provide the functionality of listing the FSK Models in a table view enabling the user to select two to four of them in preparation to join them or edit each one of them using the editor.
- The Node is dependent on some local or online models metadata  repository to provide it with list of JSON Object as an array.
- This node emits event on selection using KnimeService which is responsible for emitting it to  subscribers ( the joiner and the editor modules)
- The node should deliver the received JSON array to a java script module and this one will be used to feed an HTML table with data.
- This Node should define the received metadata JSON Array as a global window variable to play the role of shared repository between it, the Joiner and the Editor.
![image.png](https://images.zenhubusercontent.com/5f5ceabffa83aa3609e2d209/10042e86-c295-45e9-bcc4-200910b7b7ff)

**Comment by mfilter** [comment]
if "The Node is dependent on some local or online models metadata repository to provide it with list of JSON Object as an array." the way how this functionality is provided also for local repositories needs to be described in a dedicated ticket

**Comment by mfilter** [comment]
What is provided at the outport of this node? To trigger events is fine, but maybe one could also provide the selected rows from the HTML table as a KNIME table at the out port (or the corresponding JSON strings.

**Comment by mfilter** [comment]
Please also describe the Java side config menu options that are planned including if possible if  these config parameters can be set by flow variables.

**Comment by ahmadswaid** [comment]
Please find the attached workflow for your test 
[https://app.zenhub.com/files/73478810/112239dd-8234-425c-86ff-e716658e2827/download](https://app.zenhub.com/files/73478810/112239dd-8234-425c-86ff-e716658e2827/download)

**Comment by mfilter** [comment]
which update site should I use to test?
When using the current RC_2.0 I get the error message:

WARN  Repository File Chooser Configuration 3:49:0:51  File item invalid. No path provided.
WARN  List Files           3:49:0:21  "/Users/ahmadswaid/FSKDBFILES" does not exist or is not a directory
WARN  LoadWorkflowRunnable            Warnings during load: Status: Warning: FSK_DB_View 3 loaded with warnings
WARN  LoadWorkflowRunnable              Status: Warning: FSK_DB_View 3
WARN  LoadWorkflowRunnable                Status: Warning: Component 3:49
WARN  LoadWorkflowRunnable                  Status: Warning: Repository File Chooser Configuration 3:49:0:51
WARN  LoadWorkflowRunnable                    Status: Warning: State has changed from CONFIGURED to IDLE
WARN  List Files           3:49:0:21  "/Users/ahmadswaid/FSKDBFILES" does not exist or is not a directory
WARN  List Files           3:49:0:21  "/Users/ahmadswaid/FSKDBFILES" does not exist or is not a directory

**Comment by ahmadswaid** [comment]
I could have shared the workflow without reset.
could you please reset and provide a valid path to a local fskx files repository, that can be done by double clicking the container knime component and a dialog should open.
in the case that you run the fsdk db view node alone without any input it should get the list of metadata from online repository!.

**Comment by mfilter** [comment]
I now changed the path to a local directory that contains some FSKX files (among other stuff). Now I get 
WARN  FSKX Reader          3:49:0:39  Input file 'C:\Programme\KNIME\knime_4.1.3\missing' does not exist

**Comment by ahmadswaid** [comment]
Could you please check what files is listed in the output table of List Files node in the workflow
Could you please share a snapshot of the list?
if there is an error log also share please.

**Comment by mfilter** [comment]
Got it working now. There was a file in there with a special character in the file name, that already caused problems earlier.
Works fine. I close the ticket.
