### ISSUE TITLE
Support Knime highlighting feature

### ISSUE THREAD

**Issue by ahmadswaid** [SiLeBAT/FSK-Lab#666]
- This is about prepare the Joiner and the Editor to be ready to receive events on selection or edit event trigged from the FSK DB View via the Knimeservice.
- Prepare the editor to be an event publisher to the joiner or the FSK Db View.
- Prepare the joiner to be an event publisher to the editor to enable editing the combined model metadata

**Comment by mfilter** [comment]
See also my comment on the Joiner node, imho the Joiner needs to be able to publish events as well.

**Comment by mfilter** [comment]
I think this should be closes now, right?
