### ISSUE TITLE
R workspace not available after reading FSKX file that was saved after execution

### ISSUE THREAD

**Issue by mfilter** [SiLeBAT/FSK-Lab#689]
see attached file, that was written out after the Runner was executed.[https://app.zenhub.com/files/73478810/12a22109-0d2b-4fff-b7f2-c1bfa56cbeb9/download](https://app.zenhub.com/files/73478810/12a22109-0d2b-4fff-b7f2-c1bfa56cbeb9/download)

**Comment by miguelalba** [comment]
PR https://github.com/SiLeBAT/FSK-Lab/pull/694

**Comment by miguelalba** [comment]
RC 2.0.0-rc2 https://dl.bintray.com/fsk/2.0.0-rc2

**Comment by mfilter** [comment]
Assign someone who should review!

**Comment by miguelalba** [comment]
Please update to RC 2.0.0 and test the following workflow. https://github.com/SiLeBAT/FSK-Lab/files/5327205/689_missing_RData.zip

This workflow reads a combined model from file, run it to have an R workspace with results and then write it and read to/from a temporary file. The workspace is then extracted to a table that should not be empty if the workspace is retrieved.

**Comment by mfilter** [comment]
please check if the WF could be included into the test WF pipeline. Thx

**Comment by llavall** [comment]
Workflow adjusted to serve as test workflow via comparing new with expected results - uploaded to FSK_Testing on the external Server
