### ISSUE TITLE
Joiner node is not shown if inside a component

### ISSUE THREAD

**Issue by llavall** [SiLeBAT/FSK-Lab#707]
Hi all,

I don't know if that is a known issue, but I can not see the joiner ui if I wrap the node in a component and execute and view from outside. This issue seems to exist since a while.

I tested for example with 2.0.0.202010281849 in KNIME Desktop under MacOS

![Screen Shot 2020-10-29 at 12.46.06.png](https://images.zenhubusercontent.com/5e844e365580fb6378fd483a/68598070-5f32-4641-a4a0-3a17c39c9fc1)

HTH,
Lars

**Comment by ahmadswaid** [comment]
Hi Lars,
This is exactly the same error I reported before on 4.0 and 4.1.
because of that I recommended the migration of target platform to 4.2.x

**Comment by llavall** [comment]
Hi Ahmad,

I am sorry, I was not aware of that and did not intend to start a new discussion if one already exists. Can we join the ticket with yours or should I close mine?

Best,
Lars

**Comment by ahmadswaid** [comment]
please leave it open, we didn't create one for this issue yet

Thanks

**Comment by miguelalba** [comment]
Hi @llavall what version of KNIME desktop are you using?

**Comment by llavall** [comment]
Hi Miguel, 

the version is mentioned above and the site I used is development - https://dl.bintray.com/silebat/development

**Comment by ahmadswaid** [comment]
already solved, can be closed
