### ISSUE TITLE
Block writing to /tmp

### ISSUE THREAD

**Issue by llavall** [SiLeBAT/FSK-Lab#815]
Hi,

one of the newer Features of KNIME Server is blocking of writing outside of KNIME in order to avoid any security risk by users. Unfortunately, I have to override that setting to allow FSK to write to /tmp. I was wondering if we can come up with a better solution in the future.

**Comment by schuelet** [comment]
@llavall KNIME used to store data from their JavaScript based Views/Components also in the tmp folder. When the opportunity comes up, could you check if they still use the tmp folder? Maybe they have defined a new folder for generated web-page content, that we could also use.

**Comment by llavall** [comment]
@schuelet I am not aware of that. Could you please check on the Testserver? I also don't know if KNIME distinguishes into user and program access.

**Comment by mfilter** [comment]
@ahmadswaid : please have a look into this keeping also the report from @llavall from yesterday in mind.

**Comment by llavall** [comment]
I did ask KNIME recently about the new filehandling and how it is related to the /tmp folder. They told me that only the nodes that use the new filehandling schema can not write outsite of the KNIME environment anymore (if the security setting is used). This is only a mechanism that should prevent the user to decide to write on the server outside of KNIME. With other words, the use of the /tmp folder is still wanted for all relevant steps in KNIME outside of the users choice.

**Comment by mfilter** [comment]
Does this mean we can close the ticket?

**Comment by llavall** [comment]
Ja, I do not see an issue here in this context anymore - however, the developers should have that new behavior in mind.
