### ISSUE TITLE
Joiner does not concatenate metadata

### ISSUE THREAD

**Issue by mfilter** [SiLeBAT/FSK-Lab#819]
Please have a look into the following test WF: 
knime://BfR-extern/FSKX_Testing/FSK-Lab_2.0/broken_workflows/Test_MF

As you can see the metadata of the joined model is a wired mixture from both input models where a lot of the metadata (e.g. authors, creators, references) are missing. Also the expected concatenation of titles, names, scope is not available.

**Comment by schuelet** [comment]
Can confirm, only the model name has the concatenation.

**Comment by schuelet** [comment]
@ahmadswaid if the whole concatenation is not implemented, the easiest way to do it I think is in JavaScript:

check if json is array:


`
function isArray(what) {
    return Object.prototype.toString.call(what) === '[object Array]';
}
for(var i in json) {                    
    if(isArray(json[i])) {
    // concatenate array
    } else {
    // concatenate string
    }
}

`

The biggest challange is to check if the element is of controlled vocabulary, then I guess we take the entry of the last model

**Comment by ahmadswaid** [comment]
@schuelet, I agree with you on that if there is no other concerns related to  concatenation of models metadata of deffirent model classes.

**Comment by schuelet** [comment]
fixed as of SiLeBAT/FSK-Lab#825
