### ISSUE TITLE
FSK Editor JS UI is not working for long drop down list

### ISSUE THREAD

**Issue by mfilter** [SiLeBAT/FSK-Lab#820]
Please check the FSK Editor in this WF: knime://BfR-extern/FSKX_Testing/FSK-Lab_2.0/broken_workflows/Test_MF

For example list drop down list for "language written in" or "licences" is not visible to its full extend, but the user has no chance to "scroll down" the list as there is no scrollbar.
Also the "info button" for "language written in" and some other metadata fields are not working anymore, e.g. design type, measurement type, fitting procedure ..., 

Further: the usability of the view for the "Parameter" is sub-optimal, as one can only look at the columns to the rights after scrolling down to the end of the table. The scroll bar shoud be always visible, if possible

**Comment by schuelet** [comment]
fixed.
