### ISSUE TITLE
Editor JS view - corrupted display of scripts, missing visualization of images, poor handling of temp folders

### ISSUE THREAD

**Issue by mfilter** [SiLeBAT/FSK-Lab#839]
I looked into the Editor JS and found several critical issues:
- the view for model script, visualization script and Readme is currupted. I get row numbers dublicated.
- the preview on the generated visualizations is not available (not critical, but I think this worked once)
- each time the Editor visualization is opened the node creates two folders in the users AppData/Local/Temp folder: knimeViewContainerXXX and knime_chromium_dataXYZ that are only deleted after KNIME is closed (then a new folder pops up: hsperfdata_Administrator). As the KNIME server is not regularily restarted it is probably better to delete these folders already after closing the workflow. 
- I thought it was agreed, that we store information directly in the workflow and no longer in Temp folders?

**Comment by ahmadswaid** [comment]
@mfilter:
- re point 2: It's not so clear to what do you mean with preview. Do you mean the window which opens after executing the runner?
- regarding this folders created in the temp directory related to point 3&4: This is the way how knime creates the enviroment              
  to run JS nodes.
  You can watch the same behaviour if you run some nodes like: `Table View`.

**Comment by mfilter** [comment]
re point 2: we can ignore this point. I had mixed up things here.
re the folders: confirmed. Maybe @llavall can check how KNIME handles these folders on the server. Maybe there it is not a problem with that as these folders are deleted once a job is discarded. I don't know how we handle these folders on the server.

**Comment by llavall** [comment]
I only see 3 folders with the name knimeView* on the internal server in /tmp even after opening a KNIME View. I assume KNIME is reusing these folders on the server?
But the /tmp folder is full of all kinds of folders and files which seem to be created by FSK and not deleted afterwards (R, SMBL, etc.). I assume itshould fix all problems at once if we could on the server write all files in the workflows temp directory.

**Comment by mfilter** [comment]
Could you please be more specific on the folders you see? In this ticket we should focus on the folders that are linked to the JS views. We have another ticket open for the folders created by the FSK Runner

**Comment by llavall** [comment]
I can not say where the folders and files are derived from. For the mentioned knimeView* folder I only see 3  - and they seem to be reused. Maybe we can look at these files and folders together in the webmeeting and the developers give some insights.
