### ISSUE TITLE
Marcel Editor 1: Editing entries in Scope not working

### ISSUE THREAD

**Issue by Thatsreallycool** [SiLeBAT/FSK-Lab#860]
Adding entries via Editor in "Scope->Product", "Scope->Hazard", "Scope->Population group" works fine, but editing entries once saved do not lead to the Editing pop-up window.

Tested on existing models and a simple Editor with test entries with the same outcome

![editor](https://user-images.githubusercontent.com/37627583/115193340-5133b000-a0ec-11eb-80d6-ca45b66d5155.png)

**Comment by schuelet** [comment]
Here is a workflow showcasing the issue. It seems some missing values cause a null pointer exception.
knime://external-KNIME-Server/FSKX_Testing/FSK-Lab_2.0/broken_workflows/editor_bug_editing_in_scope

knime://external-KNIME-Server/FSKX_Testing/FSK-Lab_2.0/broken_workflows/editor_bug_editing_in_scope

**Comment by ahmadswaid** [comment]
@filter I have already solved it in https://github.com/SiLeBAT/FSK-Lab/pull/863, I was waiting to @schuelet to close the current ticket

**Comment by mfilter** [comment]
Marcel just tested it and for him it did not work. I assign Marcel now as well.

**Comment by mfilter** [comment]
Maybe you could have a web meeting to clarify

**Comment by ahmadswaid** [comment]
@mfilter I don't if @Thatsreallycool  tested it on a build which contains the fix.
anyway trying to contact him.

**Comment by mfilter** [comment]
@Thatsreallycool :
please confirm that this issue is solved with the latest built

**Comment by Thatsreallycool** [comment]
tested this on 
https://gitlab.bfr.berlin/silebat/repositories/raw/master/fsklab/

with this build this bug is not encountered. 
Before closing this ticket, i would suggest to wait until this can be tested on "test".

**Comment by mfilter** [comment]
seems to work now. I close this ticket. Great!
