### ISSUE TITLE
Test workflows throw errors on web portal

### ISSUE THREAD

**Issue by mfilter** [SiLeBAT/FSK-Lab#883]
Just tested 2 examples:
https://knime.bfr.berlin/knime/webportal/space/FSKX_Testing/FSK-Lab_2.0/final_test_workflows/fsk_test2_editor
=> WORKFLOW ERROR: Further workflow execution is not possible. Please check the workflow.

https://knime.bfr.berlin/knime/webportal/space/FSKX_Testing/FSK-Lab_2.0/final_test_workflows/laurent_model_test
=> ERROR FSKX Reader 26:3: Execute failed: ("FileSystemAlreadyExistsException"): null 
=> when executed on the server via local KNIME: 
ERROR FSK Runner           0:4        Execute failed: Loading required package: lattice
Loading required package: survival
Loading required package: Formula
Loading required package: ggplot2

Attaching package: 'Hmisc'

The following objects are masked from 'package:base':

    format.pval, units

Error: expr # 2 "library(tidyverse)": there is no package called 'tidyverse'
Error: expr # 8 "qte = read_excel(spreadsheet_file) %>% mutate(age.cat = cut(Age, breaks = c(3:14, 90))) %>% group_by(age.cat) %>% summarise(qte = sum(Quantite_conso, na.rm = TRUE))": could not find function "%>%"
Error: expr # 9 "qte = qte$qte[-13]": object 'qte' not found
Error: expr # 10 "qte = qte/sum(qte)": object 'qte' not found
Error: expr # 11 "pr = c(pr0[1:2], qte * (1 - sum(pr0[1:2])))": object 'qte' not found
Error: expr # 17 "res = ContTriming(runs, n, tailleM, Techvh, meanCf, sdCf, PCf, m_souillures, Se_spot, Se_sdiffuse, b)": could not find function "tibble"

**Comment by schuelet** [comment]
@mfilter The first issue is trivial but the second one is related to trying to access the same model at the same time. I see this happening more often now, would you approve assigning @miguelalba to try and find a solution to this?

**Comment by mfilter** [comment]
let's discuss with ahmad first

**Comment by ahmadswaid** [comment]
second issue is fixed in https://github.com/SiLeBAT/FSK-Lab/pull/895
