### ISSUE TITLE
Wrong controlled vocabulary used in Editor field "Format"

### ISSUE THREAD

**Issue by mfilter** [SiLeBAT/FSK-Lab#889]
the CV used under "General informat -> Format" is wrong. It seems now to show a CV on regions, but it should provide file extension of the model or data file (including version number of format if applicable). Currently we should only offer ".fskx" there. (before we also had .pmfx)
example here: knime://knime.mountpoint/FSKX_Testing/FSK-Lab_2.0/broken_workflows/testCampy(2)

**Comment by schuelet** [comment]
fixed in https://github.com/SiLeBAT/FSK-Lab/pull/891
