### ISSUE TITLE
Layout of the parameters panel in the simulator node is broken

### ISSUE THREAD

**Issue by miguelalba** [SiLeBAT/FSK-Lab#95]

**Comment by miguelalba** [comment]
Partially fixed. The rows where the parameters are defined have the same height. Still the parameters panel is right in the center and in my opinion it should next to the northwest corner.

**Comment by ahmadswaid** [comment]
![2](https://user-images.githubusercontent.com/4013295/36717083-f3a8029c-1b9c-11e8-94e7-038f6a9080b9.PNG)
![1](https://user-images.githubusercontent.com/4013295/36717085-f3c441be-1b9c-11e8-94f6-4054a0b123ba.PNG)

As I see, the parameter panel is responsive. and the parameter rows inside have alwayes padding space keep them in the center.
